### PR TITLE
Fix uppercased env

### LINKED ISSUE #3515: Environment variable names are silently changed to SCREAMING_SNAKE_CASE
### Component

agent

### Describe the bug

Our app uses the environment variable naming schema `application_name.property_name`, e.g. `matrix.environment='test'`. In 2.3.0 this worked fine, but as of 2.4.0 this is being silently changed to `MATRIX_ENVIRONMENT='test'`, which our app isn't recognizing. I can't find any option to disable this behavior in the documentation.

While I do understand that the screaming snake case is much more common than what we're using, ours is still a valid environment variable name and silently correcting it like this is causing us a ton of headache.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.4.0"}
```

### Additional context

_No response_

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

### PR DESCRIPTION
**Pull request by qwerty287**
closes #3515 

I think after this is fixed, we should publish a new release as this can be quite important.

### CODE REVIEW

**Comment by xoxys** [comment]
Uh... Do you know which PR has introduced it?

File: pipeline/frontend/yaml/compiler/settings/params.go [hunk 1]
```diff
@@ -26,15 +26,15 @@ import (
 
 // ParamsToEnv uses reflection to convert a map[string]interface to a list
 // of environment variables.
-func ParamsToEnv(from map[string]any, to map[string]string, prefix string, getSecretValue func(name string) (string, error)) (err error) {
+func ParamsToEnv(from map[string]any, to map[string]string, prefix string, upper bool, getSecretValue func(name string) (string, error)) (err error) {
```
Comment (xoxys) [inline pipeline/frontend/yaml/compiler/settings/params.go:29]: Can we call it `toUpper`? Sorry, I know a bit nitpicky.

**Review by lafriks — APPROVED** [review]

File: pipeline/frontend/yaml/compiler/settings/params.go (hunk 1 above)
Comment (xoxys) [reply pipeline/frontend/yaml/compiler/settings/params.go:29]: While I fully disagree about this way of communication, I don't care much enough to further discuss it...

**Comment by xoxys** [comment]
> Lint fail is unrelated

I can take care in a dedicated PR if you like.

File: pipeline/frontend/yaml/compiler/settings/params.go (hunk 1 above)
Comment (lafriks) [reply pipeline/frontend/yaml/compiler/settings/params.go:29]: I thumb'ed it down because in Go function param naming should be short (you will rarely find anything more then few chars let a lone multiple words with uppercase characters)

Comment (lafriks) [reply pipeline/frontend/yaml/compiler/settings/params.go:29]: sorry if I offended it with it, was not my intention

Comment (xoxys) [reply pipeline/frontend/yaml/compiler/settings/params.go:29]: No worries. I would just like to learn/hear opinions, so a plain thumbs-down says nothing to me. Thanks for adding context.
