### PR TITLE
Bitbucket DC: resolve annotated tag SHA to commit SHA before posting build status

### LINKED ISSUE #6202: Bitbucket Data Center: annotated tags don't report build status to the correct commit
### Component

server

### Describe the bug

When a repository uses annotated tags (as opposed to lightweight tags), Bitbucket Data Center's push webhook sends the tag object SHA as ToHash, not the SHA of the commit the tag is pointing to. Woodpecker uses this SHA to post build statuses back to Bitbucket, which fails silently, because the tag object SHA is not a commit.

### Steps to reproduce

Create a pipeline triggered on tag events
Push an annotated tag (git tag -a v1.0 -m "release" && git push --tags)
Pipeline runs but no build status appears on the commit in Bitbucket
Expected behavior:
Build status is displayed on Bitbucket.

### Expected behavior

Build status is displayed on Bitbucket.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-3786077c07"}
```

### Additional context

_No response_

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]

### PR DESCRIPTION
**Pull request by dccdis**
Fixes #6202

### CODE REVIEW

**Comment by qwerty287** [comment]
Thanks! The sha is also cloneable? Because cloning uses the sha by default.

**Comment by dccdis** [comment]
As far as I can tell the bug only affects status reporting. Otherwise the pipeline appears to work perfectly (code clones, runs, passes/fails) both before and after applying the proposed fix.

File: server/forge/bitbucketdatacenter/bitbucketdatacenter.go [hunk 1]
```diff
@@ -579,6 +579,14 @@ func (c *client) updatePipelineFromCommits(ctx context.Context, u *model.User, r
 	if err != nil {
 		return nil, fmt.Errorf("unable to read commit: %w", err)
 	}
+
+	// Fix for https://github.com/woodpecker-ci/woodpecker/issues/6202:
```
Comment (lafriks) [inline server/forge/bitbucketdatacenter/bitbucketdatacenter.go]: Maybe add not reference to GitHub but as a description that bitbucket in annotated tags sends tag sha not commit tag so that is clear when reading code why this is here

**Review by qwerty287 — APPROVED** [review]
