### PR TITLE
Fix bitbucket forge add repo

### LINKED ISSUE #1882: Enabling Bitbucket repo fails on local docker deployment
### Component

server

### Describe the bug

I am running a woodpecker:latest on my Mac using docker. I have connected through oAuth to the Bitbucket cloud and all the repos are listed within the UI. Trying to enable any repo (public or private) returns an error:
```
POST http://[DOMAIN]:[PORT]/api/repos?forge_remote_id={UUID}
--- HTTP 500 ---
Could not fetch repository from forge.
```
I have tried the same functionality with Github and everything worked fine.

I have seen this issue:
https://github.com/woodpecker-ci/woodpecker/issues/143
but in my case I use a DDNS and port forward so that my local instance of woodpecker server can be accessed publicly.

### System Info

```shell
Woodpecker version: `{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-eaae6b44"}`

Docker file:

# docker-compose.yml
version: '3'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:next
    ports:
      - 80:8000
      - 9000:9000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_AUTHENTICATE_PUBLIC_REPOS=true
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      # - WOODPECKER_GITHUB=true
      # - WOODPECKER_GITHUB_CLIENT=${WOODPECKER_GITHUB_CLIENT}
      # - WOODPECKER_GITHUB_SECRET=${WOODPECKER_GITHUB_SECRET}
      - WOODPECKER_BITBUCKET=true
      - WOODPECKER_BITBUCKET_CLIENT=${WOODPECKER_BITBUCKET_CLIENT}
      - WOODPECKER_BITBUCKET_SECRET=${WOODPECKER_BITBUCKET_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:next
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}

volumes:
  woodpecker-server-data:
```
```


### Additional context

I am now aware how could I grab any logs from the server.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by mzampetakis**
The workspace is a required field for ivoking bitbucket's API. While workspace is not available it must be fetched through the Repos func.

Fixes #1882

### CODE REVIEW

File: server/forge/bitbucket/bitbucket.go [hunk 1]
```diff
@@ -157,6 +157,17 @@ func (c *config) Repo(ctx context.Context, u *model.User, remoteID model.ForgeRe
...
 		name = string(remoteID)
 	}
+	repos, err := c.Repos(ctx, u)
+	if err != nil {
+		return nil, err
+	}
+	if len(owner) == 0 {
+		for _, repo := range repos {
+			if string(repo.ForgeRemoteID) == name {
+				owner = repo.Owner
```
Comment (6543) [inline server/forge/bitbucket/bitbucket.go:167]: we should `break` once we found it

**Comment by 6543** [comment]
@mzampetakis did you test it on your instance?

File: server/forge/bitbucket/bitbucket.go (hunk 1 above)
Comment (mzampetakis) [reply server/forge/bitbucket/bitbucket.go:167]: Just added that. Thanks!

**Comment by mzampetakis** [comment]
> @mzampetakis did you test it on your instance?

Yes, I tested using my personal bitbucket account and run the server locally from binaries.
Is there any proposed/expected way to provide these evidence (screenshots, API responses etc)?

**Comment by 6543** [comment]
well in this regards I trust you as long as the code looks valid ... but I wont hold you back if you want to share screenshots etc

**Review by 6543 — APPROVED** [review]

**Comment by mzampetakis** [comment]
Current implementation could not add a repo from bitbucket forge:
```
Request URL: https://DOMAIN/api/repos?forge_remote_id={REPO_UUID}
Request Method: POST
Status Code: 500
Response: Could not fetch repository from forge.
```

From the server logs: 
```
{"level":"debug","ip":"XX.XX.XX.XX","latency":183.700017,"method":"POST","path":"/api/repos","status":500,"time":"2023-06-26T21:02:39Z","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","time":"2023-06-27T00:02:39+03:00","caller":"./woodpecker/server/router/middleware/logger.go:45"}
```

Using this branch
```
Request URL: https://DOMAIN/api/repos?forge_remote_id={25ab21ea-6918-453f-bf5c-54337edb5f99}
Request Method: POST
Status Code: 200
```
and response:
```
{
    "id": 9,
    "forge_remote_id": "{25ab21ea-6918-453f-bf5c-54337edb5f99}",
    "owner": "michaliszampetakis",
    "name": "test-rp",
    "full_name": "michaliszampetakis/test-rp",
    "avatar_url": "",
    "link_url": "https://bitbucket.org/michaliszampetakis/test-rp",
    "clone_url": "https://bitbucket.org/michaliszampetakis/test-rp.git",
    "default_branch": "master",
    "scm": "git",
    "timeout": 60,
    "visibility": "public",
    "private": false,
    "trusted": false,
    "gated": false,
    "active": true,
    "allow_pr": true,
    "config_file": "",
    "cancel_previous_pipeline_events": [
        "",
        "",
        "push",
        "pull_request"
    ],
    "netrc_only_trusted": true
}
```

And the logs from the server:
```
{"level":"debug","ip":"XX.XX.XX.XX","latency":4222.696715,"method":"POST","path":"/api/repos","status":200,"time":"2023-06-26T21:08:18Z","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","time":"2023-06-27T00:08:18+03:00","caller":"./woodpecker/server/router/middleware/logger.go:45"}
```

Here are some screenshots:
Screenshot 2023-06-27 at 00 06 34
Screenshot 2023-06-27 at 00 06 26

**Comment by 6543** [comment]
ah thanks souch json objects we can also use to write unit-tests against it :D

but put that in another pull ;)
