### PR TITLE
Correct label argument parsing in agent code

### LINKED ISSUE #1704: Local agent panic, better parse WOODPECKER_FILTER_LABELS option
### Component

agent

### Describe the bug

The woodpecker-agent (next) crash with the following if one does not configure correctly the `WOODPECKER_FILTER_LABELS` option:
```console
$ export WOODPECKER_FILTER_LABELS=my-local-agent
$ go run ./cmd/agent
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.loop(0xc0001c4380)
	/home/faust/woodpecker/cmd/agent/agent.go:64 +0x1c85
github.com/urfave/cli/v2.(*Command).Run(0xc00003e2c0, 0xc0001c4380, {0xc000190010, 0x1, 0x1})
	/home/faust/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/command.go:273 +0x9eb
github.com/urfave/cli/v2.(*App).RunContext(0xc000016000, {0x1e540d0?, 0xc000198000}, {0xc000190010, 0x1, 0x1})
	/home/faust/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
	/home/faust/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/app.go:309
main.main()
	/home/faust/woodpecker/cmd/agent/main.go:42 +0x1ee
exit status 2
```

That's not a bug and it happened because of a wrong configuration, correct config is `WOODPECKER_FILTER_LABELS=agent=my-local-agent`, but IMO the agent should parse the option better and not crash since it's makes it difficult to understand where the problem is.

### System Info

```shell
docker-compose:
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-c40a6d88"}
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by 6543**
close  #1704

### CODE REVIEW

File: cmd/agent/agent.go [hunk 1]
```diff
@@ -245,3 +245,21 @@ func loop(c *cli.Context) error {
...
+	}
+	for _, v := range sl {
+		parts := strings.SplitN(v, "=", 2)
+		switch len(parts) {
+		case 2:
+			m[parts[0]] = parts[1]
+		case 1:
+			return fmt.Errorf("key '%s' does not have a value assigned", parts[0])
+		default:
+			return fmt.Errorf("empty string in slice")
```
Comment (anbraten) [inline cmd/agent/agent.go:261]: What would happen if someone uses `region=desize=large` (forgets the comma)?

Comment (6543) [reply cmd/agent/agent.go:261]: it should: `region`= `desize=large`

Comment (anbraten) [reply cmd/agent/agent.go:261]: Should we throw an error in that case as well as it will probably be an error?

**Review by anbraten — APPROVED** [review]
