### PR TITLE
skip nested GitLab repositories during sync

### LINKED ISSUE #648: support nested repositories (GitLab)
**Component:** server

### Describe the bug

It looks like Woodpecker does not properly handle nested repositories from GitLab. Nested repositories or [subgroups](https://docs.gitlab.com/ee/user/group/subgroups/) are a GitLab feature where a repository might exist inside a 2 level or greater hierarchy (e.g. `my-org-group/team-group/category-group/actual-repository.git`), as opposed to the 2 level hierarchy that is well established by SCMs (e.g. `vendor/project.git`).

When I try to sync my repositories in the Woodpecker UI, nothing happens. Looking that the `debug` error logs I get the following message:
```
{"level":"debug","time":"2021-12-31T17:45:34+01:00","message":"sync error: my-user: could not fetch permission of repo 'rootgroup/subgroup/my-repository': GET https://gitlab-instance.com/api/v4/projects/rootgroup/subgroup: 404 {message: 404 Project Not Found}"}
```

As you can see, Woodpecker is querying the wrong API endpoint:
```diff
- https://gitlab-instance.com/api/v4/projects/rootgroup/subgroup
+ https://gitlab-instance.com/api/v4/projects/rootgroup/subgroup/my-repository
```

I think there are two issues here, which can be resolved independently:
1. [ ] The complete repository sync fails/stops when only one repository fails to sync. I think Woodpecker should continue syncing the repositories and just skip the failed ones. It would be useful to display an error message to the user in that case.
2. [ ] Properly handle nested repositories. This might be harder to accomplish because they might need to be mapped to the tradition 2 level hierarchy as that's used internally?

## References
@6543 pointed out, they had replaced the GitLab API client with [github.com/xanzy/go-gitlab](github.com/xanzy/go-gitlab) in recent `master`.
- https://github.com/woodpecker-ci/woodpecker/blob/master/server/remote/gitlab/gitlab.go#L199-L207

### System Info

```shell
next-d11b2bb8
built from master@d11b2bb8e5bea6f29f82a20815ef7bf3fa96a0a2
```

### PR DESCRIPTION
**Pull request by jdoubleu**
Implements https://github.com/woodpecker-ci/woodpecker/pull/651#issuecomment-1003794674, partly fixes #648

### CODE REVIEW

**Comment by jdoubleu** [comment]
!652 makes this obsolete.

File: server/remote/gitlab/gitlab.go [hunk 1]
```diff
@@ -249,6 +250,12 @@ func (g *Gitlab) Repos(ctx context.Context, user *model.User) ([]*model.Repo, er
 			if err != nil {
 				return nil, err
 			}
+
+			if strings.Count(repo.FullName, "/") > 1 {
```
Comment (6543) [inline server/remote/gitlab/gitlab.go:254]:
```suggestion
			// TODO(648) remove when woodpecker understands nested repos
			if strings.Count(repo.FullName, "/") > 1 {
```

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
@jdoubleu thanks :)
