### PR TITLE
Fix netrc passing to clone image

### LINKED ISSUE #1837: Git clone fails due to trusted protection for netrc
### Component

server, agent

### Describe the bug

Seems like the normal clone step fails on next-101e684059 when the repo is not trusted due to the "Only inject netrc credentials into trusted containers" option that is now set by default

Is that a bug or am I doing something wrong ?

### System Info

```shell
next-101e684059
```

### Additional context

My CLone config:
```
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true
    when:
      event: tag
```
### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by anbraten**
closes #1837

### CODE REVIEW

File: pipeline/frontend/yaml/utils/image.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ func expandImage(name string) string {
 // matchImage returns true if the image name matches
```
Comment (lafriks) [inline pipeline/frontend/yaml/utils/image.go:33]:
```suggestion
// MatchImage returns true if the image name matches
```

File: pipeline/frontend/yaml/utils/image.go [hunk 2]
```diff
@@ -45,7 +45,7 @@ func matchImage(from string, to ...string) bool {
 
 // matchHostname returns true if the image hostname
```
Comment (lafriks) [inline pipeline/frontend/yaml/utils/image.go:46]:
```suggestion
// MatchHostname returns true if the image hostname
```

**Review by lafriks — CHANGES_REQUESTED** [review]

**Review by lafriks — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
