### PR TITLE
Fix gitlab hooks and simplify config extension

### LINKED ISSUE #2534: Missing root path in GitLab webhook
### Component

server

### Describe the bug

When enabling a new GitLab repository, the webhook is set in GitLab with the API address `https://example.com/api/hook`. However, the server has the `WOODPECKER_ROOT_PATH=/ci`, and it should be `https://example.com/ci/api/hook` in my case.

Changing it manually in the GitLab configuration fails because the GitLab webhook token gets erased and I don't know where to get it from, so I cannot use the webhook.

I suspect the problem is here: https://github.com/woodpecker-ci/woodpecker/blob/931af16d14e94fbf6fbb94a167251fc2d6bedded/server/forge/gitlab/gitlab.go#L450C57-L450C57

### System Info

```shell
I'm using woodpecker-server 1.0.2 in NixOS:

{"source":"https://github.com/woodpecker-ci/woodpecker","version":"1.0.2"}
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by qwerty287**
- closes #2534 
- remove `IsConfigured` func from config extension. If `server.Config.Services.ConfigService != nil` it is always configured

### CODE REVIEW

File: server/pipeline/restart.go [hunk 1]
```diff
@@ -51,8 +51,8 @@ func Restart(ctx context.Context, store store.Store, lastPipeline *model.Pipelin
 		pipelineFiles = append(pipelineFiles, &forge_types.FileMeta{Data: y.Data, Name: y.Name})
 	}
 
-	// If config extension is active we should refetch the config in case something changed
-	if server.Config.Services.ConfigService != nil && server.Config.Services.ConfigService.IsConfigured() {
+	// If the config extension is active we should refetch the config in case something changed
+	if server.Config.Services.ConfigService != nil {
```
Comment (anbraten) [inline server/pipeline/restart.go:55]: Wouldn't this also use the config service even if the url is empty?

**Review by anbraten — APPROVED** [review]
