### PR TITLE
Resolve built-in variables for global when filtered too

### LINKED ISSUE #1244: global branches filter does filter tags
make deprecated filters behave same as when filters ...

### LINKED ISSUE #1580: Github check pending when part of pipeline is cancelled via branches: [ master ]
### Component

server

### Describe the bug

When using `branches` in a pipeline and then pushing to a branch that is ignored (for example, branch dev when `branches` is `[master]`) the GitHub check on the commit never completes and still shows pending:
image

Web UI shows that the part was canceled:
image

See checks on commit: https://github.com/kyngs/LibrePremium/commit/b3991ff803c005be8a576aefca465b5472404111

### System Info

```shell
{
  "source": "https://github.com/woodpecker-ci/woodpecker",
  "version": "0.15.6"
}
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by 6543**
address https://codeberg.org/Epsilon_02/todo-checker/commit/bd461477bd074ad4a572cdda03c0c3ad119235ec

close  #1244, close #1580

### CODE REVIEW

**Comment by 6543** [comment]
one more way to make `pipeline/*` code independent from `server/*` ...

File: pipeline/frontend/metadata/environment.go [hunk 1]
```diff
@@ -0,0 +1,169 @@
...
+		sourceBranch string
+		targetBranch string
+	)
+
+	repoParts := strings.Split(m.Repo.Name, "/")
+	if len(repoParts) == 2 {
+		repoOwner = repoParts[0]
+		repoName = repoParts[1]
+	} else {
+		repoName = m.Repo.Name
```
Comment (anbraten) [inline pipeline/frontend/metadata/environment.go:39]: Note: I think it should be [repoOwner, ...repoName]

File: pipeline/frontend/metadata/environment.go [hunk 2]
```diff
@@ -0,0 +1,169 @@
...
+		"CI":                     m.Sys.Name,
+		"CI_REPO":                m.Repo.Name,
+		"CI_REPO_OWNER":          repoOwner,
+		"CI_REPO_NAME":           repoName,
+		"CI_REPO_SCM":            "git",
+		"CI_REPO_URL":            m.Repo.Link,
+		"CI_REPO_CLONE_URL":      m.Repo.CloneURL,
+		"CI_REPO_DEFAULT_BRANCH": m.Repo.Branch,
+		"CI_REPO_PRIVATE":        strconv.FormatBool(m.Repo.Private),
+		"CI_REPO_TRUSTED":        "false", // TODO should this be added?
```
Comment (anbraten) [inline pipeline/frontend/metadata/environment.go:58]: Is this ever set at some other place otherwise I would think about just removing it as its never set anyways.

File: server/pipeline/filter.go [hunk 3]
```diff
@@ -51,22 +53,20 @@ func zeroSteps(currentPipeline *model.Pipeline, forgeYamlConfigs []*forge_types.
...
-		parsedPipelineConfig, err := yaml.ParseBytes(forgeYamlConfig.Data)
+		substitutedConfigData, err := frontend.EnvVarSubst(string(forgeYamlConfig.Data), matchMetadata.Environ())
+		if err != nil {
+			log.Trace().Err(err).Msgf("fail to substitute config '%s'", forgeYamlConfig.Name)
+			return false, err
+		}
+		parsedPipelineConfig, err := yaml.ParseString(substitutedConfigData)
 		if err != nil {
-			log.Trace().Msgf("parse config '%s': %s", forgeYamlConfig.Name, err)
+			log.Trace().Err(err).Msgf("fail to parse config '%s'", forgeYamlConfig.Name)
```
Comment (anbraten) [inline server/pipeline/filter.go:69]:
```suggestion
			log.Trace().Err(err).Msgf("failed to parse config '%s'", forgeYamlConfig.Name)
```

File: server/pipeline/filter.go [hunk 4]
```diff
@@ -51,22 +53,20 @@ func zeroSteps(currentPipeline *model.Pipeline, forgeYamlConfigs []*forge_types.
...
-			},
-		},
-	}
+	matchMetadata := frontend.MetadataFromStruct(server.Config.Services.Forge, repo, p, nil, nil, "")
 
 	for _, forgeYamlConfig := range forgeYamlConfigs {
-		parsedPipelineConfig, err := yaml.ParseBytes(forgeYamlConfig.Data)
+		substitutedConfigData, err := frontend.EnvVarSubst(string(forgeYamlConfig.Data), matchMetadata.Environ())
+		if err != nil {
+			log.Trace().Err(err).Msgf("fail to substitute config '%s'", forgeYamlConfig.Name)
```
Comment (anbraten) [inline server/pipeline/filter.go:64]:
```suggestion
			log.Trace().Err(err).Msgf("failed to substitute config '%s'", forgeYamlConfig.Name)
```

File: pipeline/frontend/metadata/environment.go (hunk 2 above)
Comment (6543) [reply pipeline/frontend/metadata/environment.go:58]: I'll add this info as it's usefull for plugins like buildx

File: pipeline/frontend/metadata/environment.go (hunk 1 above)
Comment (anbraten) [reply pipeline/frontend/metadata/environment.go:39]: I meant vice versa: repo-name just the last part and owner the rest

Comment (6543) [reply pipeline/frontend/metadata/environment.go:39]: I think we should extend that in the metadata itselve: -> name, owner, id ...

Comment (6543) [reply pipeline/frontend/metadata/environment.go:39]: *ForgeID

Comment (6543) [reply pipeline/frontend/metadata/environment.go:39]: or RemoteID ?

**Comment by 6543** [comment]
@anbraten added [prepair metadata to support nested repos](https://github.com/woodpecker-ci/woodpecker/pull/1790/commits/c4c205beec6016952a90a4e78b6474aa3db00e05)

File: cli/exec/flags.go [hunk 5]
```diff
@@ -114,9 +114,14 @@ var flags = []cli.Flag{
 		Name:    "system-link",
 		Value:   "https://github.com/woodpecker-ci/woodpecker",
 	},
+	&cli.StringFlag{
+		EnvVars: []string{"CI_REPO"},
+		Name:    "repo",
+		Usage:   "full repo name",
+	},
 	&cli.StringFlag{
 		EnvVars: []string{"CI_REPO_NAME"},
```
Comment (6543) [inline cli/exec/flags.go:123]:
```suggestion
		EnvVars: []string{"CI_REPO_REMOTE_ID"},
```

File: cli/exec/metadata.go [hunk 6]
```diff
@@ -0,0 +1,116 @@
...
+	repoName := ""
+	if idx := strings.LastIndex(fullRepoName, "/"); idx != -1 {
+		repoOwner = fullRepoName[:idx]
+		repoName = fullRepoName[idx+1:]
+	}
+
+	return metadata.Metadata{
+		Repo: metadata.Repo{
+			Name:     repoName,
+			Owner:    repoOwner,
```
Comment (6543) [inline cli/exec/metadata.go:46]:
```suggestion
			Owner:    repoOwner,
			RemoteID: c.String("repo-remote-id"),
```

**Review by anbraten — APPROVED** [review]
