### PR TITLE
Fixed Pods creation of WP services

### LINKED ISSUE #3178: Pipeline with service doesn't work (K8s)
### Component

server, agent

### Describe the bug

When running pipeline with service, it going to start, but there is no pods and even attempts to create them.
There are no errors and WP pods (Server, Agent) restarts.

Pipeline:
```yaml
skip_clone: true
services:
  server:
    image: digitalocean/doks-debug
    commands:
      - echo 'This is test server' | nc -l -6 1234
    ports:
      - 1234
steps:
  client:
    image: digitalocean/doks-debug
    commands:
      - nc -v -6 -w 10 server 1234
```

Result:
Screenshot 2024-01-12

### System Info

```shell
`next-a5fa810bcc`
```

### Additional context

[woodpecker-server.log](https://github.com/woodpecker-ci/woodpecker/files/13920400/woodpecker-server.log)
[woodpecker-agent.log](https://github.com/woodpecker-ci/woodpecker/files/13920401/woodpecker-agent.log)

https://woodpecker.test.smthd.com/repos/1/pipeline/85

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by zc-devs**
Closes #3178

### CODE REVIEW

**Comment by zc-devs** [comment]
> a service should be started by SetupWorkflow so we can ignore it

[svc, err := startService(ctx, e, step)](https://github.com/woodpecker-ci/woodpecker/blob/dc734712366bc37596fe4d6c1c7eb211625362da/pipeline/backend/kubernetes/kubernetes.go#L186) just creates *Kubernetes* Service, not Woodpecker. Pod have to be created too.

File: pipeline/backend/kubernetes/kubernetes.go [hunk 1]
```diff
@@ -353,11 +348,6 @@ func (e *kube) TailStep(ctx context.Context, step *types.Step, taskUUID string)
 }
 
 func (e *kube) DestroyStep(ctx context.Context, step *types.Step, taskUUID string) error {
-	if step.Type == types.StepTypeService {
-		// a service should be stopped by DestroyWorkflow so we can ignore it
-		log.Trace().Msgf("destroyStep got service '%s', ignoring it.", step.Name)
-		return nil
-	}
 	log.Trace().Str("taskUUID", taskUUID).Msgf("Stopping step: %s", step.Name)
 	err := stopPod(ctx, e, step, defaultDeleteOptions)
```
Comment (6543) [inline pipeline/backend/kubernetes/kubernetes.go:352]: in that case the `stopPod` or `startPod` should use `stepToPodName(step)` to gen the pod name

**Comment by zc-devs** [comment]
@6543, thanks a lot for suggestion. It [works](https://woodpecker.test.smthd.com/repos/1/pipeline/121) now.
[woodpecker-agent-3227.log](https://github.com/woodpecker-ci/woodpecker/files/13999485/woodpecker-agent-3227.log)

> creating pod: server

Don't know if it matters, but now we cannot run pipelines with the same services (names) on whole namespace behind Agent.

**Review by 6543 — APPROVED** [review]
