### PR TITLE
Fix pipeline cancellation status handling and step state synchronization

### LINKED ISSUE #833: Cancle a Running Pipeline update status as failed
I expect the status to be cancled after a cancle, but when already running it shows failed

### LINKED ISSUE #2062: canceled pipelines get marked as passed (workflows stay cancled)
version: v1.0.0-rc1

when the task queue is not empty and agents are bussy, as son as there is a free slot the canceled pipeline gets marked as passed.

e.g. https://ci.woodpecker-ci.org/repos/3780/pipeline/6895

my edjucated guess is, that the task queue handler has the pipeline still in it when a pipeline gets canceled, and when it checks that entry it sees that there is nothing to do anymore and mark it green.

so there are two ways we should ensure: `canceled pipelines should not get updated as passed by the task-queue-handler` and `pipeline gets removed from task queue on cancel`

### LINKED ISSUE #2911: Cancle workflow on local backend make it as successfull
os: windows
shell: cmd.exe

### LINKED ISSUE #3848: Exit-codes are not used by server
The state send to the server contains an exit-code for the workflow. However as workflows have no exit-code they get simply ignored and are only considered by logging:

https://github.com/woodpecker-ci/woodpecker/blob/2bda19024ece0bf0deab5244fb8799f653d5adfc/agent/runner.go#L159-L175

In case of a canceled pipeline we even seem to remove the error: https://github.com/woodpecker-ci/woodpecker/blob/2bda19024ece0bf0deab5244fb8799f653d5adfc/agent/runner.go#L168

sounds to be related to #2197

### LINKED ISSUE #4349: Cancelled pipelines marked as failed
### Component

server

### Describe the bug

Sometimes pipeline cancellations still result in errors that will flag the pipeline as failed instead of cancelled:

image

### Steps to reproduce

Have not found a reliable way to reproduce this specific case.

### Expected behavior

Pipeline should be marked as cancelled instead of failed.

### System Info

```shell
next-bf5405b6cc
```

### Additional context

_No response_

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

### PR DESCRIPTION
**Pull request by 6543**
### Summary

Fixes critical issues with pipeline status updates when pipelines are cancelled or workflows are killed by the agent.
The agent's gRPC client error handling during cancellation was causing incorrect status propagation, leading to cancelled pipelines being marked as either "failed" or "success" instead of "killed".

### Problems Fixed

1. **Cancelled running pipelines show incorrect status**: When cancelling a running pipeline, the gRPC Wait() error causes the pipeline to be marked as "failed" instead of "killed"
2. **Status updates overwrite cancellation state**: Cancelled pipelines initially show correct "killed" status but get asynchronously updated to "success" 
3. **Implicit cancellation signaling**: Use explicit canceled response property instead of relying on indirect signaling (like exit codes or context errors) for cancellations
4. **Pending pipelines start after cancellation**: Race condition allows cancelled pending pipelines to begin execution when agents become available

### WebUI Screenshot showing working canceled steps & workflow
image

### Changes

- Add explicit `Canceled` field to gRPC protocol (WorkflowState and StepState) - bumps protocol version to 15
- Update agent's Wait() to return cancellation status explicitly instead of relying on errors
- Properly handle gRPC client cancellation using `context.WithCancelCause()` to distinguish cancellation reasons
- Prevent status updates from overwriting cancellation state in step status handling
- Ensure cancelled workflows remain in "killed" state throughout their lifecycle
- Add context error checking in local backend's WaitStep for cancelled workflows
- Fix defer placement in logger and tracer to ensure proper cleanup
- Improve step status state machine to handle all transitions correctly (pending→running→success/failure/killed)
- Update backend State to include Started timestamp for accurate timing
- Fix queue cleanup to handle already-deleted tasks gracefully

### Testing

Tested on both local- and docker-backend

read more at #2875

---

close #833
close #3848
close #2062
close #2911
close #4349

---

block https://github.com/woodpecker-ci/woodpecker/pull/6056
block https://github.com/woodpecker-ci/woodpecker/pull/6039

### CODE REVIEW

**Comment by 6543** [comment]
also when Wait() does not return err the step does not get cancled in the background either till it finished ?!?
-> we need special case where wait err is nil but ctx is cancled handled propperly

**Comment by 6543** [comment]
related work https://github.com/woodpecker-ci/woodpecker/pull/3850

**Comment by qwerty287** [comment]
That's nothing new…

There's a summary issue for the whole pipeline canceling: https://github.com/woodpecker-ci/woodpecker/issues/2875

**Comment by 6543** [comment]
https://github.com/6543-forks/woodpecker/blob/1b74c2baa6dd8b67577510d3dd85246ffd24d60c/agent/runner.go#L102-L113

@qwerty287 I'll work on that now ... will take some time i guess to get through all of it :)

**Comment by ghost** [comment]
@6543 What do you think about addressing this as part of this pull request, given that there are already several PRs today touching the same area?

If you’d prefer, I can also split this out into a separate PR to keep the scope tighter.
Related issue: #1870

**Comment by ghost** [comment]
Issue #2192 is partially related to pull requests #6020 and #6021, but it is not yet finalized. I will be creating a PR that can close the issue.

**Comment by 6543** [comment]
well https://github.com/woodpecker-ci/woodpecker/pull/6021 was a good cleanup in terms of code comments and the context is now right ... so i merged it as such

**Comment by 6543** [comment]
I think https://github.com/woodpecker-ci/woodpecker/pull/6020 will be obsolete once we address it properly.

**Comment by 6543** [comment]
yes mos errors related to status/state handeling come form the legacy code from drone or side efects while woodpecker did diverge form that original codes intention and there was no cleanup made ... jet

**Comment by 6543** [comment]
well cancle state is now propergated propperly:

image
image

File: pipeline/pipeline.go [hunk 1]
```diff
@@ -90,6 +90,7 @@ func (r *Runtime) MakeLogger() zerolog.Logger {
 }
 
 // Run starts the execution of a workflow and waits for it to complete.
+// TODO: here the cancle error is not propagated!
```
Comment (6543) [inline pipeline/pipeline.go]:
```suggestion
```

File: server/pipeline/workflow_status.go [hunk 2]
```diff
@@ -42,5 +42,8 @@ func UpdateWorkflowStatusToDone(store store.Store, workflow model.Workflow, stat
 	if workflow.Error != "" {
 		workflow.State = model.StatusFailure
 	}
+	if workflow.State == model.StatusKilled || state.Canceled {
```
Comment (6543) [inline server/pipeline/workflow_status.go]:
```suggestion
	if state.Canceled {
```

**Comment by 6543** [comment]
the agent listens to the server via Wait and thats the only connection we have to signal stuff from server down to agent in a push way and it only works once ... I have to thing if there are other cases where we might want to push things from server down to agent if so we should add a new interface that does that and send cancel over that else we should alter the wait just to unique signal that workfow got cancled when ended ...

**Comment by 6543** [comment]
... anywai this pull is good enouth to fix one longstanding issue right now

**Comment by ghost** [comment]
> well https://github.com/woodpecker-ci/woodpecker/pull/6021 was a good cleanup in terms of code comments and the context is now right ... so i merged it as such

Ok

**Comment by ghost** [comment]
> ... anywai this pull is good enouth to fix one longstanding issue right now

I agree

File: agent/runner.go [hunk 3]
```diff
@@ -143,9 +145,13 @@ func (r *Runner) Run(runnerCtx, shutdownCtx context.Context) error {
 	state := rpc.WorkflowState{
 		Started: time.Now().Unix(),
 	}
+
+	// Initialize workflow on the server
```
Comment (6543) [inline agent/runner.go]:
```suggestion
```

**Comment by 6543** [comment]
looks like now that we have it working we have an UI glitch:
image

File: agent/rpc/client_grpc.go [hunk 4]
```diff
@@ -177,8 +178,13 @@ func (c *client) Wait(ctx context.Context, workflowID string) (err error) {
 			// non-fatal errors
 			log.Warn().Err(err).Msgf("grpc error: wait(): code: %v", status.Code(err))
 		default:
-			log.Error().Err(err).Msgf("grpc error: wait(): code: %v", status.Code(err))
-			return err
+			switch {
+			case strings.Contains(err.Error(), "desc = queue: task canceled"):
+				return pipeline.ErrCancel
```
Comment (6543) [inline agent/rpc/client_grpc.go]: we should make that signal explicit and not relay on an queue error msg

File: rpc/proto/woodpecker.proto [hunk 5]
```diff
@@ -48,12 +48,14 @@ message StepState {
...
 
 message WorkflowState {
-  int64  started = 4;
-  int64  finished = 5;
-  string error = 6;
+  int64  started = 1;
+  int64  finished = 2;
+  string error = 3;
+  bool   canceled = 4;
 }
```
Comment (6543) [inline rpc/proto/woodpecker.proto:59]: needs more thought: should we have enum so we can signal who has canceled ... if the server canceled it or the agent e.g. because of an agent shouldown

File: rpc/peer.go [hunk 6]
```diff
@@ -67,37 +69,41 @@ type (
 )
 
 // Peer defines a peer-to-peer connection.
+// TODO: suffix Next, Wait, Init, Done and Extend with "Workflow" for docu purpose
```
Comment (6543) [inline rpc/peer.go]: this needs more docu!

File: rpc/proto/woodpecker.proto (hunk 5 above)
Comment (6543) [reply rpc/proto/woodpecker.proto:59]: similar to https://github.com/woodpecker-ci/woodpecker/issues/6024 ... or handled by it ...

File: rpc/peer.go (hunk 6 above)
Comment (ghost) [reply rpc/peer.go]:
```golang
// Peer defines the RPC interface between an agent and the Woodpecker server.
//
// It is responsible for coordinating workflow execution, including:
//   - Fetching workflows from the queue
//   - Reporting workflow and step state transitions
//   - Handling workflow completion and cancellation
//
// Method naming intentionally omits explicit "Workflow" suffixes to keep the API concise.
// The workflow or step context is defined by the parameters of each method.
```

Comment (6543) [reply rpc/peer.go]: > //   - Handling workflow completion and cancellation

duplicate to aboth

we should instead mention how Wait blocks and how ... but tjat is subject to change

also we should prefux the interface

**Comment by 6543** [comment]
## TODOs:

services dont report back when they are finished:
image

similar issue for detached steps:
image

because both are just droped into the background:
https://github.com/woodpecker-ci/woodpecker/blob/8b6c814666244d2bc0619aa4c636803b08631db8/pipeline/pipeline.go#L276-L279

File: rpc/proto/woodpecker.proto (hunk 5 above)
Comment (6543) [reply rpc/proto/woodpecker.proto:59]: nah dont takkle to much at once

**Comment by 6543** [comment]
moved last todo out as it can be handled in a next pull: #6033

File: pipeline/pipeline.go [hunk 7]
```diff
@@ -58,7 +58,8 @@ type Runtime struct {
 	engine  backend.Backend
 	started int64
 
-	ctx    context.Context
+	ctx context.Context
```
Comment (6543) [inline pipeline/pipeline.go:65]: TODO: add comment when to use wna whatvto expect and when not to use

File: rpc/peer.go [hunk 8]
```diff
@@ -15,89 +15,286 @@
...
+	//
+	// Returns:
+	//   - nil on success
+	//   - error if communication fails or server rejects the state
 	Done(c context.Context, workflowID string, state WorkflowState) error
 
-	// Extend extends the workflow deadline
+	// Extend extends the execution deadline for the workflow with the given ID.
+	//
+	// Workflows have a timeout (specified in Workflow.Timeout from Next()). Agents should
```
Comment (6543) [inline rpc/peer.go]: bad wording

File: server/rpc/server.go [hunk 9]
```diff
@@ -104,29 +109,43 @@ func (s *WoodpeckerServer) Update(c context.Context, req *proto.UpdateRequest) (
...
-func (s *WoodpeckerServer) Wait(c context.Context, req *proto.WaitRequest) (*proto.Empty, error) {
-	res := new(proto.Empty)
-	err := s.peer.Wait(c, req.GetId())
-	return res, err
+// Wait blocks until the workflow is complete.
+// Also signals via err if workflow got canceled.
+func (s *WoodpeckerServer) Wait(c context.Context, req *proto.WaitRequest) (*proto.WaitResponse, error) {
+	res := new(proto.WaitResponse)
+	res.Canceled = false
+	if err := s.peer.Wait(c, req.GetId()); err != nil {
```
Comment (6543) [inline server/rpc/server.go]: move err detection one caller up the stack

File: pipeline/backend/types/state.go [hunk 10]
```diff
@@ -16,11 +16,14 @@ package types
...
 // State defines a container state.
 type State struct {
+	// Unix start time
+	Started int64 `json:"started"`
 	// Container exit code
 	ExitCode int `json:"exit_code"`
 	// Container exited, true or false
 	Exited bool `json:"exited"`
 	// Container is oom killed, true or false
+	// TODO: well known errors as string enums into ./errors.go
```
Comment (6543) [inline pipeline/backend/types/state.go]:
```suggestion
	// TODO (6024): well known errors as string enum into ./errors.go
```

File: server/rpc/rpc.go [hunk 11]
```diff
@@ -53,6 +53,7 @@ type RPC struct {
 }
 
 // Next blocks until it provides the next workflow to execute.
+// TODO: on server shutdown release waiting agents
```
Comment (6543) [inline server/rpc/rpc.go]:
```suggestion
// TODO (6038): Server does not release waiting agents on graceful shutdown
```

File: rpc/peer.go (hunk 8 above)
Comment (6543) [reply rpc/peer.go]: c0a7a6903a187f99056d52179b733e21a5b07d8e

**Comment by 6543** [comment]
image

works :rock:

File: agent/runner.go [hunk 12]
```diff
@@ -51,6 +50,7 @@ func NewRunner(workEngine rpc.Peer, f rpc.Filter, h string, state *State, backen
 	}
 }
 
+// Run executes an workflow via an backend, tracks its state and reports back the state to the server.
```
Comment (qwerty287) [inline agent/runner.go]:
```suggestion
// Run executes a workflow using a backend, tracks its state and reports the state back to the server.
```

File: agent/runner.go [hunk 13]
```diff
@@ -143,9 +141,12 @@ func (r *Runner) Run(runnerCtx, shutdownCtx context.Context) error {
 	state := rpc.WorkflowState{
 		Started: time.Now().Unix(),
 	}
+
 	if err := r.client.Init(runnerCtx, workflow.ID, state); err != nil {
-		logger.Error().Err(err).Msg("workflow initialization failed")
-		// TODO: should we return here?
+		logger.Error().Err(err).Msg("signaling workflow initialization to server failed")
+		// This should never happen, still it did so lets clean up and end
```
Comment (qwerty287) [inline agent/runner.go]: This comment is weird ;) what should this mean? "it should never happen still it did"?

File: pipeline/pipeline.go [hunk 14]
```diff
@@ -160,8 +165,10 @@ func (r *Runtime) traceStep(processState *backend.State, err error, step *backen
 		return nil
 	}
 
+	// this is nil if the step was not started jet
```
Comment (qwerty287) [inline pipeline/pipeline.go]:
```suggestion
	// this is nil if the step was not started yet
```

And I would move the comment into the if branch

File: server/pipeline/cancel.go [hunk 15]
```diff
@@ -40,24 +40,13 @@ func Cancel(ctx context.Context, _forge forge.Forge, store store.Store, repo *mo
...
-		workflowsToCancel []string
-		workflowsToEvict  []string
-	)
-	for _, workflow := range workflows {
-		if workflow.State == model.StatusRunning {
-			workflowsToCancel = append(workflowsToCancel, fmt.Sprint(workflow.ID))
-		}
-		if workflow.State == model.StatusPending {
-			workflowsToEvict = append(workflowsToEvict, fmt.Sprint(workflow.ID))
+	var workflowsToCancel []string
```
Comment (qwerty287) [inline server/pipeline/cancel.go:43]: Is that still working with the difference between canceled and skipped status? (Workflows/steps that never started should be skipped, if they started they should be canceled)

**Review by qwerty287 — COMMENTED** [review]
I'm not really into this code, but so far it seems quite good

File: pipeline/pipeline.go (hunk 14 above)
Comment (6543) [reply pipeline/pipeline.go]: i dissagree as this would in my opinion then comment on `processState = new(backend.State)`

but happy to get an argument proving otherwise

File: server/pipeline/cancel.go (hunk 15 above)
Comment (6543) [reply server/pipeline/cancel.go:43]: yes as that is handled below:
https://github.com/woodpecker-ci/woodpecker/blob/39acb2a4be8f133b8ff011458dc84475795987ce/server/pipeline/cancel.go#L67-L82

Comment (6543) [reply server/pipeline/cancel.go:43]: the code changed here only affects the queue

(can also be observed in screenshot)

File: agent/runner.go (hunk 13 above)
Comment (6543) [reply agent/runner.go]: -> 39ce00c03b8865e57674a84940483b0dd38800c2

File: agent/runner.go [hunk 16]
```diff
@@ -90,34 +90,32 @@ func (r *Runner) Run(runnerCtx, shutdownCtx context.Context) error {
...
+		logger.Debug().Msg("start listening for server side cancel signal")
 
-			// Propagate cancellation to pipeline + backend
-			cancel()
+		if canceled, err := r.client.Wait(workflowCtx, workflow.ID); err != nil {
+			logger.Error().Err(err).Msg("server returned unexpected err while waiting for workflow to finish run")
+			cancelWorkflowCtx(err)
 		} else {
+			if canceled {
+				logger.Debug().Err(err).Msg("server side cancel signal  received")
```
Comment (lafriks) [inline agent/runner.go]:
```suggestion
				logger.Debug().Err(err).Msg("server side cancel signal received")
```

File: rpc/proto/woodpecker.proto [hunk 17]
```diff
@@ -48,12 +48,14 @@ message StepState {
...
   int32  exit_code = 5;
   string error = 6;
+  bool   canceled = 7;
 }
 
 message WorkflowState {
-  int64  started = 4;
-  int64  finished = 5;
-  string error = 6;
+  int64  started = 1;
```
Comment (lafriks) [inline rpc/proto/woodpecker.proto:55]: Is it ok that this will be a breaking change in grpc protocol?

**Comment by lafriks** [comment]
Apart from that question code LGTM

File: rpc/proto/woodpecker.proto (hunk 17 above)
Comment (6543) [reply rpc/proto/woodpecker.proto:55]: yes we have the version api that checks for that witch we are not alowed to change beside bumping the integer **in gRPC** for that

and on the same version, its fine if we break and cleanup

File: pipeline/pipeline.go (hunk 14 above)
Comment (6543) [reply pipeline/pipeline.go]: thanks for the fix btw.

... after thinking a bit and as you mentioned mentioned it so it might be best de describe this behaviour in tje function description itselfe

Comment (6543) [reply pipeline/pipeline.go]: @qwerty287 i did b69f68f3526a6cd1ebebc88c04363b9ab2db4d02 should be more clear now

**Comment by 6543** [comment]
@qwerty287 :point_up: updated the code comment and code to make it clear and more err resistant

**Review by qwerty287 — APPROVED** [review]
Seems fine to me, but untested from my side (I guess you did that…) and I'm also not totally into this code. But as @lafriks comment is solved I guess it's fine

**Comment by 6543** [comment]
deployed on our ci: https://ci.woodpecker-ci.org/repos/6106/pipeline/1778/4

**Comment by qwerty287** [comment]
@6543 there seems to be another issue: https://ci.woodpecker-ci.org/repos/3780/pipeline/31596

I canceled that manually but it's showing as succeeded

**Comment by 6543** [comment]
hmm that's another issue unrelated to agent rpc but queue implementation ... would you mind creating an issue?
