### PR TITLE
Remove `secrets` in favor of `from_secret`

### LINKED ISSUE #4413: Improve linter output for `secret:` deprecation
### Component

web-ui

### Describe the bug

If one has `secrets:` specified in WP next instead of using `environment: SECRET from_secret:` etc, the following linter message is shown

image

This is quite confusing.

I'd argue that

- The first two ones should be hidden
- The wording of the last one should be changed to something like users can directly understand and act on: "Using deprecated `secrets:` notation, please use define the secret in `environment:` instead using the `from_secret:` syntax

### Steps to reproduce

.

### Expected behavior

.

### System Info

```shell
next
```

### Additional context

_No response_

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

### PR DESCRIPTION
**Pull request by 6543**
should only be merged if https://github.com/woodpecker-ci/woodpecker/pull/4360 got merged

close  #4413

depend on  #4407

### CODE REVIEW

File: pipeline/frontend/yaml/compiler/compiler_test.go [hunk 1]
```diff
@@ -284,7 +284,9 @@ func TestCompilerCompile(t *testing.T) {
 				Name:     "step",
 				Image:    "bash",
 				Commands: []string{"env"},
-				Secrets:  []string{"missing"},
+				Environment: yaml_base_types.EnvironmentMap{
+					"MISSING": map[string]string{"from_secret": "missing"}, // TODO fix!!!
```
Comment (6543) [inline pipeline/frontend/yaml/compiler/compiler_test.go:288]: fix

**Comment by 6543** [comment]
All dependencys are merged ...

File: pipeline/frontend/yaml/linter/linter_test.go [hunk 2]
```diff
@@ -177,6 +177,14 @@ func TestLintErrors(t *testing.T) {
 			from: "{steps: { build: { image: golang, settings: { test: 'true' } } }, when: { branch: main, event: push }, clone: { git: { image: some-other/plugin-git:v1.1.0 } } }",
 			want: "Specified clone image does not match allow list, netrc is not injected",
 		},
+		{
+			from: "steps: { build: { image: golang, secrets: [ { source: mysql_username, target: mysql_username } ] } }",
+			want: "Secrets are un-supported now, use environment with from_secret",
+		},
+		{
+			from: "steps: { build: { image: golang, secrets: [ 'mysql_username' ] } }",
+			want: "Secrets are un-supported now, use environment with from_secret",
```
Comment (6543) [inline pipeline/frontend/yaml/linter/linter_test.go:186]:
```suggestion
			want: "Secrets are unsupported now, use environment with from_secret",
		},
		{
			from: "steps: { build: { image: golang, secrets: [ 'mysql_username' ] } }",
			want: "Secrets are unsupported now, use environment with from_secret",
```

File: pipeline/frontend/yaml/linter/linter.go [hunk 3]
```diff
@@ -199,12 +202,25 @@ func (l *Linter) lintSettings(config *WorkflowConfig, c *types.Container, field
...
-		return newLinterError("Should not configure both `secrets` and `settings`", config.File, fmt.Sprintf("%s.%s", field, c.Name), true)
-	}
 	return nil
 }
 
+func (l *Linter) lintContainerDeprecations(config *WorkflowConfig, c *types.Container, field string) (err error) {
+	if len(c.Secrets) != 0 {
+		err = multierr.Append(err, &errorTypes.PipelineError{
+			Type:    errorTypes.PipelineErrorTypeDeprecation,
+			Message: "Secrets are unsupported now, use environment with from_secret",
```
Comment (pat-s) [inline pipeline/frontend/yaml/linter/linter.go:212]:
```suggestion
			Message: "`secrets:` is deprecated, use `environment:` in combination with `from_secret:`"
```

File: pipeline/frontend/yaml/linter/linter_test.go [hunk 4]
```diff
@@ -177,6 +177,14 @@ func TestLintErrors(t *testing.T) {
 			from: "{steps: { build: { image: golang, settings: { test: 'true' } } }, when: { branch: main, event: push }, clone: { git: { image: some-other/plugin-git:v1.1.0 } } }",
 			want: "Specified clone image does not match allow list, netrc is not injected",
 		},
+		{
+			from: "steps: { build: { image: golang, secrets: [ { source: mysql_username, target: mysql_username } ] } }",
+			want: "Secrets are unsupported now, use environment with from_secret",
```
Comment (pat-s) [inline pipeline/frontend/yaml/linter/linter_test.go:182]:
```suggestion
			want: "`secrets:` is deprecated, use `environment:` in combination with `from_secret:`"
```

File: pipeline/frontend/yaml/linter/linter_test.go [hunk 5]
```diff
@@ -177,6 +177,14 @@ func TestLintErrors(t *testing.T) {
...
+		},
+		{
+			from: "steps: { build: { image: golang, secrets: [ 'mysql_username' ] } }",
+			want: "Secrets are unsupported now, use environment with from_secret",
```
Comment (pat-s) [inline pipeline/frontend/yaml/linter/linter_test.go:186]:
```suggestion
			want: "`secrets:` is deprecated, use `environment:` in combination with `from_secret:`"
```

**Review by pat-s — CHANGES_REQUESTED** [review]

**Comment by pat-s** [comment]
@qwerty287 If you want the error to be changed but have no time/motivation, please don't approve as otherwise it will not be changed and merged as-is.

File: pipeline/frontend/yaml/linter/linter_test.go (hunk 5 above)
Comment (xoxys) [reply pipeline/frontend/yaml/linter/linter_test.go:186]: We dont include the : after the properties in all other existing messages.

File: pipeline/frontend/yaml/linter/linter.go [hunk 6]
```diff
@@ -275,21 +291,6 @@ func (l *Linter) lintDeprecations(config *WorkflowConfig) (err error) {
 		return err
 	}
 
-	for _, container := range parsed.Steps.ContainerList {
-		if len(container.Secrets) > 0 {
-			err = multierr.Append(err, &errorTypes.PipelineError{
-				Type:    errorTypes.PipelineErrorTypeDeprecation,
-				Message: "Usage of `secrets` is deprecated, use `environment` with `from_secret`",
```
Comment (xoxys) [inline pipeline/frontend/yaml/linter/linter.go:282]: We already had proper error messages, why were they removed?

**Review by xoxys — CHANGES_REQUESTED** [review]

**Comment by zc-devs** [comment]
What's the purpose of deprecation? (warn the users)
Was it done properly? (yes)
What's the purpose of removing? (clean the code)

So, I suggest to remove it completely and just write [release](https://www.keycloak.org/docs/latest/release_notes/index.html)  and [migration](https://www.keycloak.org/docs/26.0.5/upgrading/) notes.

File: pipeline/frontend/yaml/linter/linter.go (hunk 6 above)
Comment (6543) [reply pipeline/frontend/yaml/linter/linter.go:282]: we had but just for steps, not clone or serivices ...

so thats why I initially frontport the `lintContainerDeprecations` ...

this codeblock here did not exist in 2.8 and those as i detected it i removed it because of redudancy

-> I never comparted the two messages, through i probably should have

File: pipeline/frontend/yaml/linter/linter.go [hunk 7]
```diff
@@ -199,12 +202,25 @@ func (l *Linter) lintSettings(config *WorkflowConfig, c *types.Container, field
...
-		return newLinterError("Should not configure both `secrets` and `settings`", config.File, fmt.Sprintf("%s.%s", field, c.Name), true)
-	}
 	return nil
 }
 
+func (l *Linter) lintContainerDeprecations(config *WorkflowConfig, c *types.Container, field string) (err error) {
+	if len(c.Secrets) != 0 {
+		err = multierr.Append(err, &errorTypes.PipelineError{
+			Type:    errorTypes.PipelineErrorTypeDeprecation,
+			Message: "`secrets:` is deprecated, use `environment:` in combination with `from_secret:`"
```
Comment (xoxys) [inline pipeline/frontend/yaml/linter/linter.go:212]:
```suggestion
			Message: "Usage of `secrets` is deprecated, use `environment` in combination with `from_secret`"
```

File: pipeline/frontend/yaml/linter/linter_test.go [hunk 8]
```diff
@@ -177,6 +177,14 @@ func TestLintErrors(t *testing.T) {
 			from: "{steps: { build: { image: golang, settings: { test: 'true' } } }, when: { branch: main, event: push }, clone: { git: { image: some-other/plugin-git:v1.1.0 } } }",
 			want: "Specified clone image does not match allow list, netrc is not injected",
 		},
+		{
+			from: "steps: { build: { image: golang, secrets: [ { source: mysql_username, target: mysql_username } ] } }",
+			want: "`secrets:` is deprecated, use `environment:` in combination with `from_secret:`"
```
Comment (xoxys) [inline pipeline/frontend/yaml/linter/linter_test.go:182]:
```suggestion
			want: "Usage of `secrets` is deprecated, use `environment` in combination with `from_secret`"
```

File: pipeline/frontend/yaml/linter/linter_test.go [hunk 9]
```diff
@@ -177,6 +177,14 @@ func TestLintErrors(t *testing.T) {
...
+		},
+		{
+			from: "steps: { build: { image: golang, secrets: [ 'mysql_username' ] } }",
+			want: "`secrets:` is deprecated, use `environment:` in combination with `from_secret:`"
```
Comment (xoxys) [inline pipeline/frontend/yaml/linter/linter_test.go:186]:
```suggestion
			want: "Usage of `secrets` is deprecated, use `environment` in combination with `from_secret`"
```

**Review by xoxys — COMMENTED** [review]
Sorry for being picky here, but the `:` should be removed to align with existing errors.

**Review by xoxys — DISMISSED** [review]

**Comment by pat-s** [comment]
Fair enough for now, I still think that adding a `:` to such statements makes it more clear/easier for users.

**Review by pat-s — DISMISSED** [review]

**Review by lafriks — DISMISSED** [review]

File: pipeline/frontend/yaml/linter/linter.go [hunk 10]
```diff
@@ -199,12 +202,25 @@ func (l *Linter) lintSettings(config *WorkflowConfig, c *types.Container, field
...
-		return newLinterError("Should not configure both `secrets` and `settings`", config.File, fmt.Sprintf("%s.%s", field, c.Name), true)
-	}
 	return nil
 }
 
+func (l *Linter) lintContainerDeprecations(config *WorkflowConfig, c *types.Container, field string) (err error) {
+	if len(c.Secrets) != 0 {
+		err = multierr.Append(err, &errorTypes.PipelineError{
+			Type:    errorTypes.PipelineErrorTypeDeprecation,
+			Message: "Usage of `secrets` is deprecated, use `environment` in combination with `from_secret`"
```
Comment (lafriks) [inline pipeline/frontend/yaml/linter/linter.go:212]:
```suggestion
			Message: "Usage of `secrets` is deprecated, use `environment` in combination with `from_secret`",
```

**Comment by 6543** [comment]
> we had 3 lgtms ... but they got dismissed after a code fix :/

**Review by lafriks — APPROVED** [review]
