### PR TITLE
pipeline compiler: handle nil entrys in settings list

### LINKED ISSUE #1609: CI no longer starts
### Component

server

### Describe the bug

On one of my projects CI is still triggered on push events but pipelines do not start anymore.

There is a runtime error on the server just after the push. Some other warnings complain about secrets not found but they are well defined at the organization level and the other project CIs are working fine.

Also, I can't cancel these stalled pipelines. I have already tried to reinstall Woodpecker without success.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-d35ab57f"}

Deployed on Kubernetes
Helmfile: https://github.com/Japan7/nanak8s/blob/main/apps/woodpecker/helmfile.yaml
Server chart: https://github.com/babykart/woodpecker-helm/tree/server-sts/woodpecker-server
Agent chart: https://github.com/woodpecker-ci/helm/tree/main/woodpecker-agent
```

### Additional context

```
[woodpecker-server-0] [xorm] [info]  2023/03/09 01:21:37.732964 PING DATABASE sqlite3
[woodpecker-server-0] [xorm] [info]  2023/03/09 01:21:37.732964 PING DATABASE sqlite3
[woodpecker-server-0] {"level":"error","error":"no secret found for \"registry_username\"","time":"2023-03-09T01:21:42Z","message":"paramsToEnv"}
[woodpecker-server-0] {"level":"error","error":"no secret found for \"registry_username\"","time":"2023-03-09T01:21:42Z","message":"paramsToEnv"}
[woodpecker-server-0] {"level":"error","error":"no secret found for \"webhook_id\"","time":"2023-03-09T01:21:42Z","message":"paramsToEnv"}
[woodpecker-server-0] {"level":"error","error":"no secret found for \"webhook_token\"","time":"2023-03-09T01:21:42Z","message":"paramsToEnv"}
[woodpecker-server-0] {"level":"error","error":"no secret found for \"webhook_id\"","time":"2023-03-09T01:21:42Z","message":"paramsToEnv"}
[woodpecker-server-0] 
[woodpecker-server-0] 
[woodpecker-server-0] 2023/03/09 01:21:47 [Recovery] 2023/03/09 - 01:21:47 panic recovered:
[woodpecker-server-0] runtime error: invalid memory address or nil pointer dereference
[woodpecker-server-0] /usr/local/go/src/runtime/panic.go:260 (0x454e95)
[woodpecker-server-0] /usr/local/go/src/runtime/signal_unix.go:835 (0x454e65)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/pipeline/frontend/yaml/compiler/settings/params.go:115 (0xc0b519)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/pipeline/frontend/yaml/compiler/settings/params.go:37 (0xc0ac16)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/pipeline/frontend/yaml/compiler/convert.go:82 (0xc151cd)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/pipeline/frontend/yaml/compiler/compiler.go:244 (0xc13de4)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/pipeline/stepBuilder.go:290 (0xc19f95)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/pipeline/stepBuilder.go:140 (0xc185d2)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pipeline/items.go:81 (0xc373a4)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pipeline/create.go:133 (0xc359b7)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/hook.go:178 (0xc7d198)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:173 (0xccfe8d)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/token/token.go:33 (0xccfa18)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:173 (0xc74fbc)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/user.go:72 (0xc74fa3)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:173 (0xcd523e)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/store.go:29 (0xcd5225)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:173 (0xcd4ae7)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:23 (0xcd4aca)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:173 (0xccf879)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/header/header.go:38 (0xccf7a4)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:173 (0xccf701)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/header/header.go:30 (0xccf6e6)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:173 (0xcd3eca)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:39 (0xcd3eb0)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:173 (0xa289e1)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/recovery.go:101 (0xa289cc)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:173 (0xa27850)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/gin.go:616 (0xa274b8)
[woodpecker-server-0] /woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/gin.go:572 (0xa26ffc)
[woodpecker-server-0] /usr/local/go/src/net/http/server.go:2947 (0x79510b)
[woodpecker-server-0] /usr/local/go/src/net/http/server.go:1991 (0x790326)
[woodpecker-server-0] /usr/local/go/src/runtime/asm_amd64.s:1594 (0x472920)
[woodpecker-server-0] 
[woodpecker-server-0] [xorm] [info]  2023/03/09 01:21:47.732848 PING DATABASE sqlite3
[woodpecker-server-0] [xorm] [info]  2023/03/09 01:21:47.732873 PING DATABASE sqlite3
```

https://woodpecker.japan7.bde.enseeiht.fr/Japan7/nanapi/pipeline/1

Capture d’écran 2023-03-08 à 20 37 59

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by 6543**
close #1609

### CODE REVIEW

File: pipeline/frontend/yaml/compiler/settings/params_test.go [hunk 1]
```diff
@@ -59,6 +59,11 @@ func TestParamsToEnv(t *testing.T) {
 	got := map[string]string{}
 	assert.NoError(t, ParamsToEnv(from, got, secrets))
 	assert.EqualValues(t, want, got, "Problem converting plugin parameters to environment variables")
+
+	// handle edge cases (#1609)
+	got = map[string]string{}
+	assert.NoError(t, ParamsToEnv(map[string]interface{}{"a": []interface{}{"a", nil}}, got, nil))
```
Comment (anbraten) [inline pipeline/frontend/yaml/compiler/settings/params_test.go:65]: @6543 So the yaml for that would look like this 🤔 :

```yml
a:
 a:
```

Comment (6543) [reply pipeline/frontend/yaml/compiler/settings/params_test.go:65]: well yes ... it's obvious wrong ... but it should not be able to crash the server

Comment (anbraten) [reply pipeline/frontend/yaml/compiler/settings/params_test.go:65]: Yeah sure, just wanted to understand how it would look like. Could you maybe add the yaml as a comment as well.

**Review by anbraten — APPROVED** [review]

File: pipeline/frontend/yaml/compiler/settings/params_test.go (hunk 1 above)
Comment (6543) [reply pipeline/frontend/yaml/compiler/settings/params_test.go:65]: no I already reverenced the issue id ... and it's nothing to be encouraged to do

else we would also mention miss use examples elsewhere too, we just check and if there was an issue link to it
