### PR TITLE
Use server-host as source for public links and warn if it is set to localhost

### LINKED ISSUE #142: HTTP#500 with nested HTTP#422 when trying to activate a Github Repo in Woodpecker
Given I have a running Docker Compose - Setup on Mac localhost according to https://woodpecker.laszlo.cloud/server-setup/ with Github as the driver. My docker-compose.yml is located below. I have an oauth application configured in my Github account, I can login successfully to the woodpecker UI using it and I can see my repositories.

When I click on the switch to activate my appium-experiment - repository, then I get the following error messages.
This happens for a freshly created empty test repository, too.

**UI**
Failed to activate your repository.

**Dev Tools**
```
XHRPOSThttp://localhost/api/repos/florianrein/appium-experiment
[HTTP/1.1 500 Internal Server Error 422ms]

Object { status: 500, message: "POST https://api.github.com/repos/florianrein/appium-experiment/hooks: 422 Validation Failed [{Resource:Hook Field: Code:custom}]" }
```

**As promised, my docker-compose.yml (with credentials blackened)**

```
# docker-compose.yml

version: '3'

services:
  woodpecker-server:
    image: laszlocloud/woodpecker-server:v0.9.0
    ports:
      - 80:8000
      - 9000
    volumes:
      - woodpecker-server-data:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://localhost
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=valid_oauth_client_id
      - DRONE_GITHUB_SECRET=valid_oauth_secret
      - DRONE_SECRET=some_random_hex
  woodpecker-agent:
    image: laszlocloud/woodpecker-agent:v0.9.0
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=woodpecker-server:9000
      - DRONE_SECRET=some_random_hex

volumes:
  woodpecker-server-data:
```

### LINKED ISSUE #143: HTTP#500 when trying to activate a Bitbucket Repo in Woodpecker
Given I have a running Docker Compose - Setup on Mac localhost according to https://woodpecker.laszlo.cloud/server-setup/ but with Bitbucket as the driver. My docker-compose.yml is located below. I have an oauth application configured in my Bitbucket account, I can login successfully to the woodpecker UI using it and I can see my repositories.

When I click on the switch to activate any repository, then I get the following error messages.

**UI**
Failed to activate your repository.

**Dev Tools**
```
XHRPOSThttp://localhost/api/repos/florianreinh/file_encryptgor
[HTTP/1.1 500 Internal Server Error 812ms]

Object { status: 500, message: "Bad request" }
```

**As promised, my docker-compose.yml (with credentials blackened)**
```
# docker-compose.yml
version: '3'

services:
  woodpecker-server:
    image: laszlocloud/woodpecker-server:v0.9.0
    ports:
      - 80:8000
      - 9000
    volumes:
      - woodpecker-server-data:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://localhost
      - DRONE_BITBUCKET=true
      - DRONE_BITBUCKET_CLIENT=valid_oauth_client_id
      - DRONE_BITBUCKET_SECRET=valid_oauth_secret
      - DRONE_SECRET=some_random_hex
  woodpecker-agent:
    image: laszlocloud/woodpecker-agent:v0.9.0
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=woodpecker-server:9000
      - DRONE_SECRET=some_random_hex

volumes:
  woodpecker-server-data:


```

### LINKED ISSUE #177: Incorrect usage of X-Forwarded-For
`X-Forwarded-For` header contains HTTP _client_ address as seen by reverse proxy...

https://en.wikipedia.org/wiki/X-Forwarded-For
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
https://docs.oracle.com/en-us/iaas/Content/Balance/Reference/httpheaders.htm

...but in

https://github.com/laszlocph/woodpecker/blob/master/shared/httputil/httputil.go#L70

it seems to be used for HTTP server hostname calculation. Same problem with XFF, X-Real-IP probably.

### LINKED ISSUE #247: Use server-host / DRONE_HOST as source for the public domain
Currently the request address being used to access the webinterface is for example used as base for webhooks and some links.

This is done by using `httputil.GetURL(c.Request)`. Maybe it would be nice to use the `DRONE_HOST` string for these places. Currently `DRONE_HOST` is only used for the automatic letsencrypt setup.

Using the domain a user requested the webinterface with brings some problems:
- if you use multiple domains to access the webinterface the current domain would be used instead of a specific one
- you can not develop with localhost => would for example register webhooks to github, ... with localhost which is denied

### PR DESCRIPTION
**Pull request by anbraten**
closes #247 

- Currently the domain (hostname and schema) for public links (mainly webhooks) is gathered from the request url some client accessed the api from
   -  It could be dangerous if the server is listening under some unintentional address 
   -  It could lead to problems where the ui is accessed by some private ip etc
   - It make the setup simpler if `DRONE_SERVER` is used for all public domains (has to be configured anyways)

resolves #143 
resolves #142 
resolves #177, 

- The additional `localhost` check helps to identify problems as described by #143 (`localhost` and private ips can not be used with most most VCS-systems)

### CODE REVIEW

**Comment by 6543** [comment]
followup of  #175

File: server/configFetcher.go [hunk 1]
```diff
@@ -15,14 +15,23 @@ type configFetcher struct {
 	build   *model.Build
 }
 
+func NewConfigFetcher(remote remote.Remote, user *model.User, repo *model.Repo, build *model.Build) *configFetcher {
```
Comment (6543) [inline server/configFetcher.go:18]:
```suggestion
func newConfigFetcher(remote remote.Remote, user *model.User, repo *model.Repo, build *model.Build) *configFetcher {
```

File: server/configFetcher_test.go [hunk 2]
```diff
@@ -14,11 +15,11 @@ func TestFetchGithub(t *testing.T) {
 	if err != nil {
 		t.Fatal(err)
 	}
-	configFetcher := &configFetcher{
-		remote_: github,
-		user:    &model.User{Token: "xxx"},
-		repo:    &model.Repo{Owner: "laszlocph", Name: "drone-multipipeline", Config: ".drone"},
-		build:   &model.Build{Commit: "89ab7b2d6bfb347144ac7c557e638ab402848fee"},
-	}
+	configFetcher := server.NewConfigFetcher(
```
Comment (6543) [inline server/configFetcher_test.go:18]:
```suggestion
	configFetcher := server.newConfigFetcher(
```

**Review by 6543 — APPROVED** [review]
