### PR TITLE
Postgress can exec Sync2 after migration only in own transactions

### LINKED ISSUE #518: Latest Docker Image does not work
### Component

server

### Describe the bug

I tried updating my docker-compose setup to the latest version, but the server didn't came up. The only logs I got (using `--log-level=trace`) is this:

```
woodpecker_1        | {"time":"2021-11-21T16:24:16Z","message":"LogLevel = trace"}
woodpecker_1        | {"level":"trace","time":"2021-11-21T16:24:16Z","message":"Remote (gitea) opts: gitea.Opts{URL:\"https://git.sp-codes.de\", Context:\"continuous-integration/woodpecker\", Client:\"...\", Secret:\"...\", Username:\"\", Password:\"\", PrivateMode:false, SkipVerify:false}"}
woodpecker_1        | {"level":"trace","time":"2021-11-21T16:24:16Z","message":"setup datastore: store.Opts{Driver:\"postgres\", Config:\"postgres://...:...@database/woodpecker?sslmode=disable\"}"}
woodpecker_1        | {"level":"trace","time":"2021-11-21T16:24:16Z","message":"start migration task 'xorm'"}
woodpecker_1        | {"level":"info","time":"2021-11-21T16:24:17Z","message":"migration task 'xorm' done"}
woodpecker_1        | {"level":"trace","time":"2021-11-21T16:24:17Z","message":"start migration task 'alter-table-drop-repo-fallback'"}
woodpecker_1        | {"level":"trace","time":"2021-11-21T16:24:17Z","message":"migration task 'alter-table-drop-repo-fallback' exist"}
woodpecker_1        | {"level":"trace","time":"2021-11-21T16:24:17Z","message":"start migration task 'drop-allow-push-tags-deploys-columns'"}
woodpecker_1        | {"level":"trace","time":"2021-11-21T16:24:17Z","message":"migration task 'drop-allow-push-tags-deploys-columns' exist"}
woodpecker_1        | [xorm] [warn]  2021/11/21 16:24:17.102343 Table agents column agent_id db type is SERIAL, struct type is BIGSERIAL
woodpecker_1        | [xorm] [warn]  2021/11/21 16:24:17.102375 Table agents column agent_capacity db type is INTEGER, struct type is BIGINT
woodpecker_1        | [xorm] [warn]  2021/11/21 16:24:17.102379 Table agents column agent_created db type is INTEGER, struct type is BIGINT
woodpecker_1        | [xorm] [warn]  2021/11/21 16:24:17.102383 Table agents column agent_updated db type is INTEGER, struct type is BIGINT
```

### System Info

```shell
Not available, because the server didn't start.
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

### PR DESCRIPTION
**Pull request by 6543**
close #518

### CODE REVIEW

File: server/store/datastore/migration/migration.go [hunk 1]
```diff
@@ -128,7 +128,11 @@ func runTasks(sess *xorm.Session, tasks []task) error {
 	return nil
 }
 
-func syncAll(sess *xorm.Session) error {
+type syncEngine interface {
+	Sync2(beans ...interface{}) error
+}
+
+func syncAll(sess syncEngine) error {
```
Comment (anbraten) [inline server/store/datastore/migration/migration.go:135]: Why do we need this interface?

**Review by anbraten — APPROVED** [review]

File: server/store/datastore/migration/migration.go (hunk 1 above)
Comment (6543) [reply server/store/datastore/migration/migration.go:135]: To pass engine and session without having same func wtice

Comment (6543) [reply server/store/datastore/migration/migration.go:135]: Tld: postgrss do not allow us to use sync2 twice in one transaction at all.
mysql does have problems with that too, but tjere i worked around :)
