### PR TITLE
Fix pipeline status calculation/reporting

### LINKED ISSUE #1895: Statuses are not correctly calculated/reported
### Component

server

### Describe the bug

1. https://ci.woodpecker-ci.org/repos/3780/pipeline/6235/31 fails, but the pipeline is marked as success.
2. 

### System Info

```shell
our ci
```

### Additional context

Could be related to https://github.com/woodpecker-ci/woodpecker/issues/1871 and https://github.com/woodpecker-ci/woodpecker/issues/1893

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by qwerty287**
Closes #1895 
Regression of #1784

### CODE REVIEW

File: server/model/workflow.go [hunk 1]
```diff
@@ -73,3 +73,16 @@ func PipelineStatus(workflows []*Workflow) StatusValue {
...
 	return status
 }
+
+// WorkflowStatus determine workflow status based on corresponding step list
+func WorkflowStatus(steps []*Step) StatusValue {
+	status := StatusSuccess
+
+	for _, p := range steps {
+		if p.Failing() {
+			status = p.State
```
Comment (6543) [inline server/model/workflow.go:83]: break

**Review by 6543 — APPROVED** [review]
