### PR TITLE
Fix send on closed channel panic in SSE stream handlers

### LINKED ISSUE #6454: woodpecker server panics & crashes at times
### Component

server

### Describe the bug

Since updating to 3.14.0-rc.0 I've noticed occasional woodpecker-server crashes due to a pnic in pubsub handling

```
panic: send on closed channel

goroutine 686109 [running]:
go.woodpecker-ci.org/woodpecker/v3/server/api.EventStreamSSE.func2.1({{0x1ffe5ee33080, 0x1a}, {0x1ffe64404000, 0xbb12, 0xc000}})
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:104 +0x65
created by go.woodpecker-ci.org/woodpecker/v3/server/pubsub/memory.(*publisher).Publish in goroutine 686088
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pubsub/memory/pub.go:58 +0x415
panic: send on closed channel

goroutine 685741 [running]:
go.woodpecker-ci.org/woodpecker/v3/server/api.EventStreamSSE.func2.1({{0x1ffe5d334a00, 0x1a}, {0x1ffe5f334000, 0xad83, 0xc000}})
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/stream.go:104 +0x65
created by go.woodpecker-ci.org/woodpecker/v3/server/pubsub/memory.(*publisher).Publish in goroutine 685740
        /woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pubsub/memory/pub.go:58 +0x415
```

### Steps to reproduce

I've not been able to trace the root cause yet, the server keeps running for some time, given my current woodpecker-server installation I've seen multiple restarts due to these crashes:
```
woodpecker                      woodpecker-server-0                                               1/1     Running             25 (11h ago)    47h                                                                                                         
```

### Expected behavior

_No response_

### System Info

```shell
kubernetes runner, bitbucket-server,
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-a7739a2bb7"}
```

### Additional context

_No response_

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]

### PR DESCRIPTION
**Pull request by hhamalai**
Instead of explicitly closing channels which leads to concurrency issues with channels being used after close, allow channels to be GC'ed.

Remove the recover block that was previously catching&masking the panics in the LogStreamSSE. EventStreamSSE was missing the same

fixes: #6454

### CODE REVIEW

File: server/api/stream_test.go [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+		topic := map[string]struct{}{pubsub.PublicTopic: {}}
+
+		done := make(chan struct{})
+		go func() {
+			defer close(done)
+			EventStreamSSE(c)
+		}()
+
+		// Let the event handler subscribe
+		time.Sleep(20 * time.Millisecond)
```
Comment (utafrali) [inline server/api/stream_test.go]: `time.Sleep(20ms)` for synchronization is fragile. Under a loaded CI runner, the goroutine spawned inside `EventStreamSSE` may not have reached the `Subscribe` call (and registered the receiver in the pubsub map) before the sleep expires, meaning the test publishes messages before the subscription is live and misses the race it is trying to reproduce.

A more reliable approach is to instrument the scheduler with a hook or use a channel to signal readiness. For example, the `memory.Subscribe` registers the receiver before blocking, so you could wrap the broker to notify a ready channel on the first Subscribe call:
```go
type notifyingBroker struct {
    pubsub.PubSub
    subscribed chan struct{}
}
func (n *notifyingBroker) Subscribe(c context.Context, t pubsub.Topics, r pubsub.Receiver) error {
    close(n.subscribed)
    return n.PubSub.Subscribe(c, t, r)
}
```
This removes the timing dependency entirely.

File: server/api/stream.go [hunk 2]
```diff
@@ -249,6 +238,7 @@ func LogStreamSSE(c *gin.Context) {
 			log.Error().Err(err).Msg("tail of logs failed")
 		}
 
+		close(batches)
```
Comment (utafrali) [inline server/api/stream.go:248]: `close(batches)` and `cancel(err)` are called back-to-back without waiting for the inner goroutine to finish draining the channel. When `Tail()` returns naturally (end of a finished pipeline), the inner goroutine may still have buffered log entries to serialize and forward to `logChan`. Calling `cancel(nil)` immediately causes the main select loop to exit via `ctx.Done()` and emit the `eof` event before those trailing entries are delivered to the client.

A wait group would fix this:
```go
var innerDone sync.WaitGroup
innerDone.Add(1)
go func() {
    defer innerDone.Done()
    for entries := range batches { ... }
}()

err := server.Config.Services.Logs.Tail(ctx, step.ID, batches)
close(batches)
innerDone.Wait() // drain before signalling eof
cancel(err)
```
Note that the `Wait()` itself is safe because the inner goroutine's select also watches `ctx.Done()`, so if the context is cancelled from the outside (client disconnect) before `Tail()` returns, the inner goroutine will exit promptly and `Wait()` will not block.

File: server/api/stream_test.go [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+				})
+			}()
+		}
+
+		// Simulate client disconnect mid-publish.
+		cancel()
+		wg.Wait()
+		<-done
+	}
+}
```
Comment (utafrali) [inline server/api/stream_test.go:160]: Missing newline at end of file (`\ No newline at end of file` in the diff). `gofmt` and most Go tooling expect a trailing newline.

File: server/api/stream_test.go [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+
+	"github.com/gin-gonic/gin"
+
+	"go.woodpecker-ci.org/woodpecker/v3/server"
+	"go.woodpecker-ci.org/woodpecker/v3/server/pubsub"
+	"go.woodpecker-ci.org/woodpecker/v3/server/pubsub/memory"
+	"go.woodpecker-ci.org/woodpecker/v3/server/scheduler"
+)
+
+func TestEventStreamSSE_ConcurrentDisconnect(t *testing.T) {
```
Comment (utafrali) [inline server/api/stream_test.go]: The test covers the `EventStreamSSE` concurrent-disconnect scenario, which is good. However, `LogStreamSSE` was also fixed in this PR (removal of the `recover` block, new select, adding `close(batches)`). A parallel test for `LogStreamSSE` would give confidence that the nested-goroutine path is also race-free. The two-goroutine structure there (outer goroutine wrapping `Tail`, inner goroutine ranging over `batches`) is harder to reason about and more deserving of a race-detector test.

**Review by utafrali — APPROVED** [review]
The core fix is correct and is a genuine improvement: removing `close(eventChan)` / `close(logChan)` from defers eliminates the send-on-closed-channel panics, the updated selects properly unblock on context cancellation (better than the old `default`-fallthrough pattern), and adding `close(batches)` fixes a pre-existing goroutine leak in `LogStreamSSE`. The main concerns are test fragility (timing-based sync) and a potential last-entries-lost race when a log stream ends naturally before the inner goroutine drains its buffer.

**Comment by 6543** [comment]
now I dont know why there are tow pulls working on the same issue by the same people either authored or reviewed!?!?

-> https://github.com/woodpecker-ci/woodpecker/pull/6455

**Comment by hhamalai** [comment]
> now I dont know why there are tow pulls working on the same issue by the same people either authored or reviewed!?!?
> 
> -> #6455

How you wish to proceed @6543 I suspected the another PR was agent generated as the unit tests still weren't testing against the right fix, and the further commits introduced more regression. Happy to close this one, as the other PR has a good start.

**Comment by 6543** [comment]
well i prevere human interaction, if llms are used is fine as long as it's just a tool, the contributor has to own its mistakes and also understand the code ...

I will look into both pulls and then decide what to take from what ... give me time to do so :)

File: server/api/stream_test.go (hunk 1 above)
Comment (6543) [reply server/api/stream_test.go]: fine by me as is

**Review by 6543 — APPROVED** [review]
nice work
