### PR TITLE
Sanitize pod's step label

### LINKED ISSUE #3272: kubernetes backend - step name with spaces causes label error
### Component

agent

### Describe the bug

Having a pipline like:
```
steps:
  - name: build image
    image: plugins/docker
```

on a woodpecker 2.2.2 server with kubernetes backend I get the following error:
```
Pod "wp-01hmywxc67eps76kjkryer0rc6" is invalid: metadata.labels: Invalid value: "build image": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

This has worked before on the 2.1.x version

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"2.2.2"}
```

### Additional context

_No response_

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

### PR DESCRIPTION
**Pull request by zc-devs**
Closes #3272

### CODE REVIEW

File: pipeline/backend/kubernetes/utils_test.go [hunk 1]
```diff
@@ -54,3 +54,17 @@ func TestDNSName(t *testing.T) {
 	_, err = dnsName("abc\\def")
 	assert.ErrorIs(t, err, ErrDNSPatternInvalid)
 }
+
+func TestToDnsName(t *testing.T) {
+	name, err := toDNSName("BUILD_AND_DEPLOY_0")
+	assert.NoError(t, err)
+	assert.Equal(t, "build-and-deploy-0", name)
```
Comment (6543) [inline pipeline/backend/kubernetes/utils_test.go:61]: error case missing

**Review by 6543 — APPROVED** [review]

File: pipeline/backend/kubernetes/pod_test.go [hunk 2]
```diff
@@ -40,18 +40,27 @@ func TestStepToPodName(t *testing.T) {
...
-	assert.EqualValues(t, "clone", name)
+	assert.EqualValues(t, "postgres", name)
+}
+
+func TestStepLabel(t *testing.T) {
+	name, err := stepLabel(&types.Step{Name: "Build image"})
+	assert.NoError(t, err)
+	assert.EqualValues(t, "build-image", name)
+
+	name, err = stepLabel(&types.Step{Name: ".build.image"})
```
Comment (6543) [inline pipeline/backend/kubernetes/pod_test.go:62]:
```suggestion
	_, err = stepLabel(&types.Step{Name: ".build.image"})
```

File: pipeline/backend/kubernetes/utils_test.go [hunk 3]
```diff
@@ -54,3 +54,20 @@ func TestDNSName(t *testing.T) {
...
+
+	name, err = toDNSName("build and deploy")
+	assert.NoError(t, err)
+	assert.Equal(t, "build-and-deploy", name)
+
+	name, err = toDNSName("build & deploy")
+	assert.NoError(t, err)
+	assert.Equal(t, "build--deploy", name)
+
+	name, err = toDNSName("-build-and-deploy")
```
Comment (6543) [inline pipeline/backend/kubernetes/utils_test.go:71]:
```suggestion
	_, err = toDNSName("-build-and-deploy")
```
