### PR TITLE
Fix pipeline backend autodetect

### LINKED ISSUE #542: agent: backend detection do not work
### Component

agent

### Describe the bug

When updated to the latest image of the woodpecker-agent, d8daf87ccbb1 as of 7 hours ago, my agent no longer is able to connect to backend engine. Last used image was image pulled at 2021-11-25T12:32:10

### System Info

```shell
Version:next-5e6b38e0

woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    networks:
      - t2_proxy
      - woodpecker
    volumes:
      - $DOCKERDIR/woodpecker:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=xxxx
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=xxx
      - WOODPECKER_GITEA_CLIENT=xxxx
      - WOODPECKER_GITEA_SECRET=xxxx
      - WOODPECKER_AGENT_SECRET=xxxx
    labels:
      - "traefik.enable=true"
      - "diun.enable=true"
      - "flame.type=application" # "app" works too
      - "flame.name=woodpecker"
      # HTTP Routers
      - "traefik.http.routers.woodpecker-rtr.entrypoints=https"
      - "traefik.http.routers.woodpecker-rtr.rule=Host(`woodpecker.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.woodpecker-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.woodpecker-rtr.service=woodpecker-svc"
      - "traefik.http.services.woodpecker-svc.loadbalancer.server.port=8000"

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent
    command: agent
    restart: always
    networks:
      - woodpecker
    depends_on:
      - woodpecker-server
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=xxxx
```

### Additional context

```shell
021-11-26T19:13:50.956301366Z {"level":"error","error":"Can't detect an avivable backend engine","time":"2021-11-26T19:13:50Z","message":"cannot find backend engine 'auto-detect'"}
2021-11-26T19:13:51.485319646Z {"level":"error","error":"Can't detect an avivable backend engine","time":"2021-11-26T19:13:51Z","message":"cannot find backend engine 'auto-detect'"}
2021-11-26T19:13:52.012249226Z {"level":"error","error":"Can't detect an avivable backend engine","time":"2021-11-26T19:13:52Z","message":"cannot find backend engine 'auto-detect'"}
2021-11-26T19:13:52.754148047Z {"level":"error","error":"Can't detect an avivable backend engine","time":"2021-11-26T19:13:52Z","message":"cannot find backend engine 'auto-detect'"}
2021-11-26T19:13:53.869578042Z {"level":"error","error":"Can't detect an avivable backend engine","time":"2021-11-26T19:13:53Z","message":"cannot find backend engine 'auto-detect'"}
2021-11-26T19:13:55.818519427Z {"level":"error","error":"Can't detect an avivable backend engine","time":"2021-11-26T19:13:55Z","message":"cannot find backend engine 'auto-detect'"}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

### PR DESCRIPTION
**Pull request by 6543**
close #542

### CODE REVIEW

File: pipeline/backend/docker/docker.go [hunk 1]
```diff
@@ -17,28 +17,31 @@ import (
...
-func (e *engine) Name() string {
+func (e *docker) Name() string {
 	return "docker"
 }
 
-func (e *engine) IsAvivable() bool {
-	_, err := os.Stat("/.dockerenv")
-	return os.IsNotExist(err)
+func (e *docker) IsAvailable() bool {
+	_, err := os.Stat("/var/run/docker.sock")
```
Comment (anbraten) [inline pipeline/backend/docker/docker.go:39]: Strange I don't get why this wasn't working. I checked a clean container for that file. Using the docker sock for detection only works as we are mounting it to the agent, but should be fine for now.

**Review by anbraten — APPROVED** [review]

File: pipeline/backend/docker/docker.go (hunk 1 above)
Comment (6543) [reply pipeline/backend/docker/docker.go:39]: well `/.dockerenv` detect if agent is within an container ... but that was never what we should check for - we like to know it we have access to an docker daemon :)
