### PR TITLE
Fix pipeline cancel

### LINKED ISSUE #6184: Kubernetes backend continues to execute on cancelled pipeline execution
### Component

agent

### Describe the bug

I noticed plausible regression with how Kubernetes backend schedules and executes steps when user cancel the pipeline. On UI the running step is receiving logs after the cancel is hit, after the step pod completes, following steps are not producing logs to UI, but the step pods are executed on my local kind cluster. 

I bisected the change to 06818ee6adc563c0c48767eac21a67aba313c1ba / https://github.com/woodpecker-ci/woodpecker/pull/6056 . Before that the running step pods were terminated and no further execution were happening.

With the changes from that commit the line in screenshot is evaluated false (state.error == ErrExternal) and nil is returned, and there's not checks for pipeline cancellations.

### Steps to reproduce

With a kubernetes backend
- run a pipeline
- cancel it while a step is running
- observe logs are still produced on Woodpecker UI and further steps are executed on cluster

### Expected behavior

Running step pods should be cancelled, no further execution of the remaining pipeline steps

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"dev"} 
Running from 06818ee6adc563c0c48767eac21a67aba313c1ba
Kubernetes backend with `kind`
```

### Additional context

_No response_

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]

### PR DESCRIPTION
**Pull request by 6543**
close #6184

### CODE REVIEW

File: pipeline/runtime/workflow.go [hunk 1]
```diff
@@ -53,7 +53,7 @@ func (r *Runtime) Run(runnerCtx context.Context) error {
 
 	r.started = time.Now().Unix()
 
-	if err := r.engine.SetupWorkflow(runnerCtx, r.spec, r.taskUUID); err != nil {
+	if err := r.engine.SetupWorkflow(r.ctx, r.spec, r.taskUUID); err != nil {
```
Comment (6543) [inline pipeline/runtime/workflow.go]: to be able to cancle while workflow is setup

File: pipeline/backend/docker/docker.go [hunk 2]
```diff
@@ -267,6 +267,8 @@ func (e *docker) WaitStep(ctx context.Context, step *backend_types.Step, taskUUI
 		log.Trace().Msgf("ContainerWait returned with resp: %v", resp)
 	case err := <-errC:
 		log.Trace().Msgf("ContainerWait returned with err: %v", err)
+	case <-ctx.Done():
```
Comment (6543) [inline pipeline/backend/docker/docker.go:270]: `ContainerWait` should respect the parent context cancelation, but this makes sure we do so in any case

File: agent/runner.go [hunk 3]
```diff
@@ -51,6 +51,8 @@ func NewRunner(workEngine rpc.Peer, f rpc.Filter, h string, state *State, backen
 	}
 }
 
+// TODO: refactor this big function into subfunctions in it's own subpackage
+
```
Comment (6543) [inline agent/runner.go:55]: unrelated, i can move that out if wanted...

File: server/queue/fifo.go [hunk 4]
```diff
@@ -169,10 +169,7 @@ func (q *fifo) Wait(ctx context.Context, taskID string) error {
 		select {
 		case <-ctx.Done():
 		case <-state.done:
-			// only return queue errors and no workflow errors
-			if !errors.Is(state.error, new(ErrExternal)) {
```
Comment (6543) [inline server/queue/fifo.go:173]: this is the simple fix ... that lets us cancle again

**Comment by 6543** [comment]
:point_up: needs review feedback :)

File: pipeline/runtime/workflow.go (hunk 1 above)
Comment (6543) [inline pipeline/runtime/workflow.go]:
```suggestion
	if err := r.engine.SetupWorkflow(r.ctx, r.spec, r.taskUUID); err != nil { //nolint:contextcheck
```

**Comment by 6543** [comment]
now with root cause fix:

# cancled
image

# successful failed
image

# sucessfull success
image

**Comment by 6543** [comment]
I dislike the current queue interface anywa... I will refactor this away with #6317
