### PR TITLE
Let normal repo admins change timeout to lower values

### LINKED ISSUE #179: Default Timeout value in build settings cannot be changed
In Woodpecker built from b52e404f93ccea05dc783aa929770c4a0fad2e74 one cannot change value of field `Timeout` in build task settings. After changing default value 60 to 30 error "Filed to update the respository settings" popups and setting is not changed.

No such problem with other settings on the same page i.e. `Pipeline Path`.

Regards,
Paweł

### LINKED ISSUE #534: Insufficient privileges when changing settings on my own project
### Component

server

### Describe the bug

Using Gitea and the latest Woodpecker, I added some projects and am able to run CI jobs on them. However, whenever I change settings, like the timeout, it says I have insufficient privileges. I only have the one user.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-4891f104"}
```

### Additional context

```shell
Thank you!
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

### PR DESCRIPTION
**Pull request by 6543**
close #534
close #179

### CODE REVIEW

File: server/api/repo.go [hunk 1]
```diff
@@ -31,14 +31,18 @@ import (
 	"github.com/woodpecker-ci/woodpecker/shared/token"
 )
 
+// TODO: system wide default timeout and max timeout
```
Comment (6543) [inline server/api/repo.go:34]:
```suggestion
// TODO: make it set system wide via environment variables
```

File: server/api/repo.go [hunk 2]
```diff
@@ -108,8 +114,12 @@ func PatchRepo(c *gin.Context) {
 		return
 	}
 
-	if (in.IsTrusted != nil || in.Timeout != nil) && !user.Admin {
-		c.String(403, "Insufficient privileges")
+	if in.Timeout != nil && *in.Timeout > maxTimeout && !user.Admin {
+		c.String(http.StatusForbidden, "timeout is higher than max timeout on this instance")
+	}
+	if in.IsTrusted != nil && *in.IsTrusted != repo.IsTrusted && !user.Admin {
```
Comment (anbraten) [inline server/api/repo.go:120]: Is this the fix for #534?

**Review by anbraten — APPROVED** [review]

File: server/api/repo.go (hunk 2 above)
Comment (6543) [reply server/api/repo.go:120]: `&& *in.IsTrusted != repo.IsTrusted` - yes it looks like the new ui send IsTrusted field even if not changed :)

so you could call it a "frontend"-issue but I like to harden the backend so this should just also do/fix it

Comment (anbraten) [reply server/api/repo.go:120]: Ahh yip, I changed it to always send the complete from instead of the previous behavior were the form was directly submitted on click or key-input with only the specific part.
