### PR TITLE
sync repo permissions on login

### LINKED ISSUE #1666: Updating user permissions on login
https://codeberg.org/Codeberg-CI/feedback/issues/66  
https://github.com/woodpecker-ci/woodpecker/issues/485  
https://github.com/woodpecker-ci/woodpecker/pull/1658#discussion_r1143782278

### LINKED ISSUE #1851: Missing Permissions for users of same org
### Component

server

### Describe the bug

Scenario:
User A and B are members of the same org on gitea.
Both have admin permissions to the repo in question.

When User A activates the repo in woodpecker, i would expect User B to be able to see the repository in their feed.

I think #1658 change the behavior here and this used to be the case.

When manually navigating as User B to the repo in woodpecker the server logs
`Error fetching permission for <user> <repo>. sql: no rows in result set`
and the repo becomes permanently visible in their feed.

### System Info

```shell
Woodpecker next-b5b3b957
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by bkleiner**
if indeed a bug, fixes #1851 after re-log

close #1666

### CODE REVIEW

File: server/api/login.go [hunk 1]
```diff
@@ -145,6 +145,30 @@ func HandleAuth(c *gin.Context) {
 		return
 	}
 
+	repos, err := _store.RepoListAll(true)
```
Comment (6543) [inline server/api/login.go:148]: well instead of itterate over all repos, wouldn't it be better to get the list a user has acces to from the forge?

in any case we need to be carefull as souch a large-scale-sync do hit api rate limits fast!!!

Comment (bkleiner) [reply server/api/login.go]: > well instead of itterate over all repos, wouldn't it be better to get the list a user has acces to from the forge?

right - switched to that way of handling it, makes it much simpler too.

> in any case we need to be carefull as souch a large-scale-sync do hit api rate limits fast!!!

yeah about that, the `user_synced` attribute was dropped recently. https://github.com/woodpecker-ci/woodpecker/pull/1658/files and i couldn't find a good other attribute this could tie to.
Should we reintroduce it?

Comment (6543) [reply server/api/login.go]: well in this regards I think we should just encourage to not logout and in all the time ... the session can stay logged in quite some time D:

Comment (bkleiner) [reply server/api/login.go]: fair enough - imho it would be nice if these were refreshed without a re-log (we have _a lot_ of traffic on our ci)
but thats outside of the scope of this PR anyway so  ¯\_(ツ)_/¯

File: server/api/login.go [hunk 2]
```diff
@@ -145,6 +145,41 @@ func HandleAuth(c *gin.Context) {
...
+	}
+
+	for _, forgeRepo := range repos {
+		dbRepo, err := _store.GetRepoForgeID(forgeRepo.ForgeRemoteID)
+		if err != nil && errors.Is(err, types.RecordNotExist) {
+			continue
+		}
+		if err != nil {
+			log.Error().Msgf("cannot list repos for %s. %s", u.Login, err)
+			c.Redirect(http.StatusSeeOther, "/login?error=internal_error")
```
[the remark this answers is not in the document]
Comment (bkleiner) [reply server/api/login.go:162]: i guess this relates to line 148 and following, the db query here should always succeed.
i really don't know about swallowing _all_ errors. you would want to let users know that it can't list the repos from the forge, wouldn't you?
So _imho_ if one wanted to ignore rate-limit errors here, it should check only for that. (which would require re-working _all_ the forge clients)

[the remark this answers is not in the document]
Comment (bkleiner) [reply server/api/login.go:162]: that's completely besides what i saying but ok...
