### PR TITLE
Respect WOODPECKER_GITEA_SKIP_VERIFY (#1152)

### LINKED ISSUE #605: WOODPECKER_GITEA_SKIP_VERIFY is no effect
### Component

server

### Describe the bug

I set both `WOODPECKER_GITEA_SKIP_VERIFY=true` and `DRONE_GITEA_SKIP_VERIFY=true` in docker environment but still get the error `x509: certificate signed by unknown authority` . My server is using cert sign by `Encryption Everywhere DV TLS CA - G1`. Any help?

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"v0.14.3"}
```

### Additional context

```shell
time="2021-12-13T09:27:56Z" level=error msg="cannot authenticate user. Post \"https://******/login/oauth/access_token\": x509: certificate signed by unknown authority"
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

### PR DESCRIPTION
**Pull request by 6543**
backport #1152
close #605

### CODE REVIEW

File: server/remote/gitea/gitea.go [hunk 1]
```diff
@@ -76,18 +77,32 @@ func New(opts Opts) (remote.Remote, error) {
 	}, nil
 }
 
+// Name returns the string name of this driver
+func (c *Gitea) Name() string {
+	return "gitea"
+}
+
```
Comment (6543) [inline server/remote/gitea/gitea.go:84]:
```suggestion
```

**Review by jolheiser — APPROVED** [review]
