### PR TITLE
Use step uuid instead of name in GRPC status calls

### LINKED ISSUE #3109: Allow steps/services to have same name
See https://github.com/woodpecker-ci/woodpecker/pull/3079

Services can't have names that steps have, also adding another step `clone` does not work.

I think we can also disallow this but then we should add a linter for it.

### PR DESCRIPTION
**Pull request by 6543**
close #3109

~~also fix start time of steps to be set correctly~~ edgecase do not hit anymore as we have a clear sepperation between workflows and steps now :)

### CODE REVIEW

File: pipeline/rpc/peer.go [hunk 1]
```diff
@@ -61,16 +61,16 @@ type Peer interface {
...
 
-	// Done signals the workflow is complete
+	// Done signals the step is complete
 	Done(c context.Context, id string, state State) error
 
 	// Extend extends the workflow deadline
 	Extend(c context.Context, id string) error
 
-	// Update updates the workflow state
+	// Update updates step state
```
Comment (6543) [inline pipeline/rpc/peer.go:73]:
```suggestion
	// Update updates the step state
```

**Comment by 6543** [comment]
image

**Comment by 6543** [comment]
this config:
```yaml
clone:
    cline:
        image: "bash"
        commands:
            - sleep 10s

steps:
    wait:
        image: "bash"
        commands:
            - "echo type: step"
            - "sleep 15s"

services:
    wait:
        image: "bash"
        commands:
            - "echo type: service"
            - "sleep 15s"
```

image

**Comment by anbraten** [comment]
@6543 Why isn't it using the service icons in your UI: https://github.com/woodpecker-ci/woodpecker/pull/3078

**Comment by 6543** [comment]
@anbraten see  #3148 :D

**Comment by anbraten** [comment]
thanks for #3148

File: server/grpc/rpc.go [hunk 2]
```diff
@@ -106,29 +106,38 @@ func (s *RPC) Update(_ context.Context, id string, state rpc.State) error {
 
 	workflow, err := s.store.WorkflowLoad(workflowID)
 	if err != nil {
-		log.Error().Msgf("error: rpc.update: cannot find workflow with id %d: %s", workflowID, err)
+		log.Error().Msgf("rpc.update: cannot find workflow with id %d: %s", workflowID, err)
```
Comment (anbraten) [inline server/grpc/rpc.go:109]:
```suggestion
		log.Error().Err(err).Msgf("rpc.update: cannot find workflow with id %d", workflowID)
```

File: server/grpc/rpc.go [hunk 3]
```diff
@@ -106,29 +106,38 @@ func (s *RPC) Update(_ context.Context, id string, state rpc.State) error {
...
 		return err
 	}
 
 	currentPipeline, err := s.store.GetPipeline(workflow.PipelineID)
 	if err != nil {
-		log.Error().Msgf("error: cannot find pipeline with id %d: %s", workflow.PipelineID, err)
+		log.Error().Msgf("cannot find pipeline with id %d: %s", workflow.PipelineID, err)
```
Comment (anbraten) [inline server/grpc/rpc.go:115]:
```suggestion
		log.Error().Err(err).Msgf("cannot find pipeline with id %d", workflow.PipelineID)
```

File: server/grpc/rpc.go [hunk 4]
```diff
@@ -106,29 +106,38 @@ func (s *RPC) Update(_ context.Context, id string, state rpc.State) error {
...
 		return err
 	}
 
-	step, err := s.store.StepChild(currentPipeline, workflow.PID, state.Step)
+	step, err := s.store.StepByUUID(state.StepUUID)
 	if err != nil {
-		log.Error().Msgf("error: cannot find step with name %s: %s", state.Step, err)
+		log.Error().Msgf("cannot find step with uuid %s: %s", state.StepUUID, err)
```
Comment (anbraten) [inline server/grpc/rpc.go:121]:
```suggestion
		log.Error().Err(err).Msgf("cannot find step with uuid %s", state.StepUUID)
```

File: server/grpc/rpc.go [hunk 5]
```diff
@@ -106,29 +106,38 @@ func (s *RPC) Update(_ context.Context, id string, state rpc.State) error {
...
 		return err
 	}
 
+	if step.PipelineID != currentPipeline.ID {
+		msg := fmt.Sprintf("agent return status with step uuid '%s' of step, witch does not belonging to current pipeline", state.StepUUID)
```
Comment (anbraten) [inline server/grpc/rpc.go:126]:
```suggestion
		msg := fmt.Sprintf("agent returned status with step uuid '%s' which does not belong to current pipeline", state.StepUUID)
```

File: server/grpc/rpc.go [hunk 6]
```diff
@@ -106,29 +106,38 @@ func (s *RPC) Update(_ context.Context, id string, state rpc.State) error {
...
+			Int64("stepPipelineID", step.PipelineID).
+			Int64("currentPipelineID", currentPipeline.ID).
+			Msg(msg)
+		return fmt.Errorf(msg)
+	}
+
 	repo, err := s.store.GetRepo(currentPipeline.RepoID)
 	if err != nil {
-		log.Error().Msgf("error: cannot find repo with id %d: %s", currentPipeline.RepoID, err)
+		log.Error().Msgf("cannot find repo with id %d: %s", currentPipeline.RepoID, err)
```
Comment (anbraten) [inline server/grpc/rpc.go:136]:
```suggestion
		log.Error().Err(err).Msgf("cannot find repo with id %d", currentPipeline.RepoID)
```

File: server/pipeline/stepStatus.go [hunk 7]
```diff
@@ -34,14 +34,10 @@ func UpdateStepStatus(store model.UpdateStepStore, step *model.Step, state rpc.S
...
 		}
-	} else {
+	} else if step.Stopped == 0 {
 		step.Started = state.Started
 		step.State = model.StatusRunning
 	}
-
-	if step.Started == 0 && step.Stopped != 0 {
-		step.Started = started
-	}
```
Comment (anbraten) [inline server/pipeline/stepStatus.go:44]: Could you explain why this isn't needed?

Comment (6543) [reply server/pipeline/stepStatus.go:44]: Because of the check `if step.Stopped == 0`

without the check there are edgecases where could be the case a stoped steped can be markt as running again, witch is wrong.

I do remember we have "running" steps indefinetly in cancled pipelines. This could be the fix, i just did not test that specific.

Anyway the func hat a good testcoverage ... so just look at the tests

Comment (6543) [reply server/pipeline/stepStatus.go:44]: I'll split it out into a new pull

**Review by anbraten — APPROVED** [review]

**Comment by 6543** [comment]
as i wrote, did split questioned change into #3151
