### PR TITLE
Fix workflow hang on services

### LINKED ISSUE #6506: Woodpecker services dont stop
best example is the 'server' service in security scan at https://ci.woodpecker-ci.org/repos/3780/pipeline/33822

witch was manually killed by me.

I suspect 4dd3be7f96a976d19facfc86837bfbc18a974f6f (https://github.com/woodpecker-ci/woodpecker/pull/6471)

And will debug more into it...

### PR DESCRIPTION
**Pull request by 6543**
close https://github.com/woodpecker-ci/woodpecker/issues/6506 ; regression of https://github.com/woodpecker-ci/woodpecker/pull/6471

because we now wait for all steps to trace status back before we return, the defere did not tear down services anymore ...

... we now explicit tear down services and steps after all stages have executed.

I also added tests to check for that and update the dummy backend to fullfill the interface contract of killing all "_running_" steps with DestroyWorkflow

### CODE REVIEW

File: pipeline/backend/dummy/dummy.go [hunk 1]
```diff
@@ -258,10 +269,16 @@ func (e *dummy) DestroyStep(_ context.Context, step *backend_types.Step, taskUUI
...
 	if !exist {
 		return fmt.Errorf("expect env of workflow %s to exist but found none to destroy", taskUUID)
 	}
+	wc, ok := rawWC.(chan struct{})
+	if !ok {
+		return fmt.Errorf("workflow stop chan not found")
+	}
+	close(wc)
+
 	e.kv.Delete("task_" + taskUUID)
```
Comment (6543) [inline pipeline/backend/dummy/dummy.go]:
```suggestion
	e.kv.Delete(workflowKey(taskUUID))
```

**Review by xoxys — APPROVED** [review]

**Comment by 6543** [comment]
thx & sorry that i did not catched such easy bug first ...

**Comment by xoxys** [comment]
No worries. Happens, as I approved it I could have tested it better as well. However, `main` is expected to contain bugs from time to time.
