### PR TITLE
Fix oauth file envvars

### LINKED ISSUE #1479: the `*_FILE` values are not sanitized/cleaned sending control characters to upstream oAuth servers
### Component

server, web-ui

### Describe the bug

When providing the forge client and secret via file (likely also other values, but I've stumbled across these) control characters are not stripped, this causes oAuth to fail as there is as %0A in the id / secret passed to the upstream oAuth server.

I've hit this problem while using `WOODPECKER_GITEA_CLIENT_FILE` and `WOODPECKER_GITEA_SECRET_FILE`, while one can work around this by doing an `echo -n "value" > file`, when adding manually, many secrets providers and tools always have at least the %0A (\0) at the end of string (even when it's just a single line/string), also good luck when preparing these files from a non *nix os.

### System Info

```shell
next-a3f4f305 on Linux
```

### Additional context

When using editors / tools providing the file:

File:
```text
<client-id stripped>

```

Results in
`https://codeberg.org/login/oauth/authorize?client_id=<client-id stripped>%0A%0A&redirect_uri=...`

File:
```text
<client-id stripped>
```
Results in
`https://codeberg.org/login/oauth/authorize?client_id=<client-id stripped>%0A&redirect_uri=...`

---
When doing the `echo -n "" >file` or `cat createdWithEditorOrTool | awk '{printf $1}' > file` trick, there is no control character at the end, and it works as intended.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by danial23**
Fixes a bug (introduced with #1417) where setting environment variables of the form WOODPECKER_\<forge\>\_CLIENT_FILE and WOODPECKER_\<forge\>\_SECRET_FILE had no effect.

Also fixes #1479.

### CODE REVIEW

File: server/services/setup.go [hunk 1]
```diff
@@ -114,8 +115,8 @@ func setupForgeService(c *cli.Context, _store store.Store) error {
 		_forge.AdditionalOptions = make(map[string]any)
 	}
 
-	_forge.Client = c.String("forge-oauth-client")
-	_forge.ClientSecret = c.String("forge-oauth-secret")
+	_forge.Client = strings.TrimRight(c.String("forge-oauth-client"), "\r\n")
```
Comment (anbraten) [inline server/services/setup.go:118]: Mabye even `TrimSpace` to remove unexpected `\t` and ` ` as well.

File: server/services/setup.go [hunk 2]
```diff
@@ -114,8 +115,8 @@ func setupForgeService(c *cli.Context, _store store.Store) error {
...
+	_forge.ClientSecret = strings.TrimRight(c.String("forge-oauth-secret"), "\r\n")
```
Comment (anbraten) [inline server/services/setup.go:119]:
```suggestion
	_forge.Client = strings.TrimSpace(c.String("forge-oauth-client"), "\r\n")
	_forge.ClientSecret = strings.TrimSpace(c.String("forge-oauth-secret"), "\r\n")
```

**Review by anbraten — APPROVED** [review]

File: server/services/setup.go [hunk 3]
```diff
@@ -114,8 +115,8 @@ func setupForgeService(c *cli.Context, _store store.Store) error {
 		_forge.AdditionalOptions = make(map[string]any)
 	}
 
-	_forge.Client = c.String("forge-oauth-client")
-	_forge.ClientSecret = c.String("forge-oauth-secret")
+	_forge.Client = strings.TrimSpace(c.String("forge-oauth-client"), "\r\n")
+	_forge.ClientSecret = strings.TrimSpace(c.String("forge-oauth-secret"), "\r\n")
```
Comment (anbraten) [inline server/services/setup.go:119]:
```suggestion
	_forge.Client = strings.TrimSpace(c.String("forge-oauth-client"))
	_forge.ClientSecret = strings.TrimSpace(c.String("forge-oauth-secret"))
```
