### PR TITLE
Fix server panic

### LINKED ISSUE #3424: Server panic on manual run & push
### Component

server

### Describe the bug

In the latest version I can not get a pipeline to run in any repository.

The pipelines get created but return a message of "No pipeline steps available!"
In the logs for the server I see a panic recovered. I have included the logs below.

### System Info

```shell
next-901315625b
```

### Additional context

{"level":"info","time":"2024-02-23T10:12:20Z","message":"log level: info"}
{"level":"info","time":"2024-02-23T10:12:20Z","message":"starting Woodpecker server with version 'next-901315625b'"}

2024/02/23 10:14:15 [Recovery] 2024/02/23 - 10:14:15 panic recovered:
assignment to entry in nil map
/usr/local/go/src/runtime/map_faststr.go:205 (0x41ae3a)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/pipeline/frontend/yaml/compiler/compiler.go:187 (0xe9f5f4)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pipeline/stepbuilder/stepBuilder.go:297 (0xed31be)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pipeline/stepbuilder/stepBuilder.go:166 (0xed1a52)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pipeline/stepbuilder/stepBuilder.go:88 (0xed122c)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pipeline/items.go:90 (0xed8de7)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/pipeline/create.go:86 (0xed6c04)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/api/pipeline.go:66 (0xefb96b)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xeefa81)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/repo.go:191 (0xeef8fc)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xeef861)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/repo.go:166 (0xeef6dc)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xc2adca)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/repo.go:157 (0xf69e24)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xc2adca)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/repo.go:71 (0xf6983d)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xf62402)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/token/token.go:32 (0xf623f0)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xc2adca)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/session/user.go:69 (0xf6b8d9)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xc2adca)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/store.go:28 (0x129e2ce)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xc2adca)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/logger.go:37 (0x129e385)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xf62217)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/header/header.go:38 (0xf62144)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xf62098)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/middleware/header/header.go:30 (0xf62086)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xf68727)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/server/router/router.go:44 (0xf68715)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xc37979)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/recovery.go:102 (0xc37967)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/context.go:174 (0xc3678d)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/gin.go:620 (0xc3641c)
/woodpecker/src/github.com/woodpecker-ci/woodpecker/vendor/github.com/gin-gonic/gin/gin.go:576 (0xc35f51)
/usr/local/go/src/net/http/server.go:3137 (0x82b26d)
/usr/local/go/src/net/http/server.go:2039 (0x8264c7)
/usr/local/go/src/runtime/asm_amd64.s:1695 (0x4808c0)

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

### PR DESCRIPTION
**Pull request by qwerty287**
Closes #3424

### CODE REVIEW

**Review by anbraten — APPROVED** [review]

File: pipeline/frontend/yaml/compiler/compiler.go [hunk 1]
```diff
@@ -179,9 +179,10 @@ func (c *Compiler) Compile(conf *yaml_types.Workflow) (*backend_types.Config, er
 			cloneSettings["tags"] = "true"
 		}
 		container := &yaml_types.Container{
-			Name:     defaultCloneName,
-			Image:    cloneImage,
-			Settings: cloneSettings,
+			Name:        defaultCloneName,
+			Image:       cloneImage,
+			Settings:    cloneSettings,
+			Environment: map[string]any{},
```
Comment (lafriks) [inline pipeline/frontend/yaml/compiler/compiler.go:185]: Imho this is the way:

```suggestion
			Environment: map[string]any,
```
