### PR TITLE
Fix pipeline cancel API endpoint and update Web and CLI clients

### LINKED ISSUE #1369: Broken Cancel Pipeline in Web UI and CLI
### Component

server, cli, web-ui

### Describe the bug

There is a breaking change in #1331 (deletion of line 88 in `server/router/api.go`)

image

This endpoint is used by both the clients (web and cli), so they are breaking now.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"dev"}
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by dvjn**
Fixes #1369 

Implemented @anbraten's suggestions in https://github.com/woodpecker-ci/woodpecker/issues/1369#issuecomment-1296208261

### CODE REVIEW

File: woodpecker-go/woodpecker/client.go [hunk 1]
```diff
@@ -253,9 +253,9 @@ func (c *client) PipelineStart(owner, name string, num int, params map[string]st
 }
 
 // PipelineStop cancels the running step.
-func (c *client) PipelineStop(owner, name string, num, step int) error {
-	uri := fmt.Sprintf(pathStep, c.addr, owner, name, num, step)
-	err := c.delete(uri)
+func (c *client) PipelineStop(owner, name string, num int) error {
+	uri := fmt.Sprintf(pathStop, c.addr, owner, name, num)
```
Comment (anbraten) [inline woodpecker-go/woodpecker/client.go:257]:
```suggestion
func (c *client) PipelineStop(owner, name string, pipeline int) error {
	uri := fmt.Sprintf(pathStop, c.addr, owner, name, pipeline)
```

**Review by anbraten — APPROVED** [review]

**Review by 6543 — APPROVED** [review]
