### PR TITLE
Delete GitLab webhooks with partial URL match

### LINKED ISSUE #4248: GitLab: disabling repo doesn't remove webhook
### Component

server

### Describe the bug

Gitlab.org, GL 17.6

### Steps to reproduce

1. Enable repo 
2. Disable repo (red error appears in the bottom right)
3. Repo is disabled in WP dashboard but the Webhook still exists 

### Expected behavior

Webhook gets removed without error

### System Info

```shell
WP next-9dd796ad65 (Oct 13th 2024)
GL 17.6
```

### Additional context

_No response_

### Validations

- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]

### PR DESCRIPTION
**Pull request by pat-s**
fix #4248 

- [x] Ensure to process all matching webhooks and don't exit after the first one
- [x] Use partial string match as `webURL` != `hook.URL` (the latter always has the `api/token` suffix, the former doesn't)

Tested on gitlab.com.

### CODE REVIEW

File: server/forge/gitlab/gitlab.go [hunk 1]
```diff
@@ -553,28 +553,26 @@ func (g *GitLab) Deactivate(ctx context.Context, user *model.User, repo *model.R
...
-				break
+				_, err = client.Projects.DeleteProjectHook(_repo.ID, hookID, gitlab.WithContext(ctx))
+				log.Info().Msg(fmt.Sprintf("successfully deleted hook with ID %d for repo %s", hookID, repo.FullName))
+				if err != nil {
+					return err
+				}
 			}
 		}
 
 		// Exit the loop when we've seen all pages
```
Comment (anbraten) [inline server/forge/gitlab/gitlab.go:566]: The comment doesn't fit anymore:
```suggestion
```

File: server/forge/gitlab/gitlab.go [hunk 2]
```diff
@@ -553,28 +553,26 @@ func (g *GitLab) Deactivate(ctx context.Context, user *model.User, repo *model.R
...
-		if resp.CurrentPage >= resp.TotalPages {
+		if hookID != -1 || resp.CurrentPage >= resp.TotalPages {
```
Comment (anbraten) [inline server/forge/gitlab/gitlab.go:567]: Looks like it would still stop after the first page with a match `hookID != -1`? 😉 

```suggestion
		if resp.CurrentPage >= resp.TotalPages {
```

Comment (pat-s) [reply server/forge/gitlab/gitlab.go:567]: OK yes, in this new format we can just skim through all pages and don't need a custom exit logic.

**Review by 6543 — APPROVED** [review]

**Comment by 6543** [comment]
```
server/forge/gitlab/gitlab.go:544:2: ineffectual assignment to hookID (ineffassign)
	hookID := -1
	^
```
