### PR TITLE
Remove xterm and use ansi converter for logs

### LINKED ISSUE #998: Task log output colors have numbering also colored
### Component

web-ui

### Describe the bug

Line numbers are also colored if log output has term colors.

attels

### System Info

```shell
21534252303b8def38905e0b56e3a0faed5c71c4
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### LINKED ISSUE #1012: Terminal issues
### Component

web-ui

### Describe the bug

I noticed some issues with the new terminal:
- log lines for other running jobs shown in running jobs as well? 🤔  or the terminal is not properly reset after switching
- `exit code x` pushed to bottom (only half of it visible)
- space reserved for `exit code x` for running jobs
- sometimes it still seems to flicker

Screenshot from 2022-07-05 09-28-45

Screenshot from 2022-07-05 09-27-57

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-3f73d5bf"}
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by lafriks**
* Steaming works without flickering
* Text can be correctly copied
* Show only selected step output when streaming
* Improved exit code colors for better readability
* Adds time display on right side

When compiled assets/Build.js size was 355K, now it is 26K

Fixes #1012 
Fixes #998

Screenshots:

attels

attels

### CODE REVIEW

**Comment by 6543** [comment]
we first make sure the issues that termJS saved are still saved after this merge

**Comment by lafriks** [comment]
Fixed all remaining issues that was not yet covered

**Comment by lafriks** [comment]
Did a small improvement to show only unique time points:
attels

File: web/src/components/repo/build/BuildLog.vue [hunk 1]
```diff
@@ -110,24 +116,94 @@ export default defineComponent({
...
+
+    function write(lines: LogLine[]) {
+      let lastLine = 0;
+      if (log.value.length > 0) {
+        lastLine = log.value[log.value.length - 1].line;
+      }
+      if (logBatch.length > 0 && logBatch[logBatch.length - 1].line > lastLine) {
+        lastLine = logBatch[logBatch.length - 1].line;
+      }
+      for (let i = 0; i < lines.length; i += 1) {
```
[the remark this answers is not in the document]
Comment (lafriks) [reply web/src/components/repo/build/BuildLog.vue:145]: for of construct is not allowed by eslint rule https://eslint.org/docs/latest/rules/no-restricted-syntax

File: web/src/components/repo/build/BuildLog.vue [hunk 2]
```diff
@@ -188,16 +270,26 @@ export default defineComponent({
 
       if (isProcFinished(proc.value)) {
         const logs = await apiClient.getLogs(repo.value.owner, repo.value.name, build.value.number, proc.value.pid);
-        term.value.write(
+        write(
           logs
-            .slice(Math.max(logs.length, 0) - 300, logs.length) // TODO: think about way to support lazy-loading more than last 300 logs (#776)
-            .map((line) => `${(line.pos || 0).toString().padEnd(logs.length.toString().length)}  ${line.out}`)
-            .join(''),
+            .slice(Math.max(logs.length, 0) - maxLineCount, logs.length) // TODO: think about way to support lazy-loading more than last 300 logs (#776))
```
[the remark this answers is not in the document]
Comment (lafriks) [reply web/src/components/repo/build/BuildLog.vue]: @qwerty287 fixec

**Comment by 6543** [comment]
Important: is output sanitized? -> XSS !!!

**Comment by lafriks** [comment]
> Important: is output sanitized? -> XSS !!!

@6543 yes ansi_up library does both - console color rendering and html escaping

**Comment by anbraten** [comment]
@lafriks Could you try those adjustments of the `BuildLog` file.

```vue
<template>
  <div v-if="build" class="flex flex-col pt-10 md:pt-0">
    <div
      class="fixed top-0 left-0 w-full md:hidden flex px-4 py-2 bg-gray-600 dark:bg-dark-gray-800 text-gray-50"
      @click="$emit('update:proc-id', null)"
    >
      <span>{{ proc?.name }}</span>
      <Icon name="close" class="ml-auto" />
    </div>

    <div
      class="flex flex-grow flex-col bg-gray-300 dark:bg-dark-gray-700 md:m-2 md:mt-0 md:rounded-md overflow-hidden"
      @mouseover="showActions = true"
      @mouseleave="showActions = false"
    >
      <div v-show="showActions" class="absolute top-0 right-0 z-50 mt-2 mr-4 hidden md:flex">
        <Button
          v-if="proc?.end_time !== undefined"
          :is-loading="downloadInProgress"
          :title="$t('repo.build.actions.log_download')"
          start-icon="download"
          @click="download"
        />
      </div>

      <div
        v-show="loadedLogs"
        ref="consoleElement"
        class="
          w-full
          max-w-full
          grid grid-cols-[min-content,1fr,min-content]
          auto-rows-min
          flex-grow
          p-2
          gap-x-2
          overflow-x-hidden overflow-y-auto
        "
      >
        <div v-for="line in log" :key="line.index" class="contents font-mono">
          <span class="text-gray-500 whitespace-nowrap select-none text-right">{{ line.index + 1 }}</span>
          <!-- eslint-disable-next-line vue/no-v-html -->
          <span class="align-top text-color whitespace-pre-wrap break-words" v-html="line.text" />
          <span class="text-gray-500 whitespace-nowrap select-none text-right">{{ formatTime(line.time) }}</span>
        </div>
      </div>

      <div class="m-auto text-xl text-color">
        <span v-if="proc?.error" class="text-red-400">{{ proc.error }}</span>
        <span v-else-if="proc?.state === 'skipped'" class="text-red-400">{{ $t('repo.build.actions.canceled') }}</span>
        <span v-else-if="!proc?.start_time">{{ $t('repo.build.step_not_started') }}</span>
        <div v-else-if="!loadedLogs">{{ $t('repo.build.loading') }}</div>
      </div>

      <div
        v-if="proc?.end_time !== undefined"
        :class="proc.exit_code == 0 ? 'dark:text-lime-400 text-lime-700' : 'dark:text-red-400 text-red-600'"
        class="w-full bg-gray-200 dark:bg-dark-gray-800 text-md p-4"
      >
        {{ $t('repo.build.exit_code', { exitCode: proc.exit_code }) }}
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import '~/style/console.css';

import AnsiUp from 'ansi_up';
import { debounce } from 'lodash';
import { computed, defineComponent, inject, nextTick, onMounted, PropType, Ref, ref, toRef, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import Button from '~/components/atomic/Button.vue';
import Icon from '~/components/atomic/Icon.vue';
import useApiClient from '~/compositions/useApiClient';
import useNotifications from '~/compositions/useNotifications';
import { Build, Repo } from '~/lib/api/types';
import { findProc, isProcFinished, isProcRunning } from '~/utils/helpers';

type LogLine = {
  index: number;
  text: string;
  time?: number;
};

export default defineComponent({
  name: 'BuildLog',

  components: { Icon, Button },

  props: {
    build: {
      type: Object as PropType<Build>,
      required: true,
    },

    // used by toRef
    // eslint-disable-next-line vue/no-unused-properties
    procId: {
      type: Number,
      required: true,
    },
  },

  emits: {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    'update:proc-id': (procId: number | null) => true,
  },

  setup(props) {
    const notifications = useNotifications();
    const i18n = useI18n();
    const build = toRef(props, 'build');
    const procId = toRef(props, 'procId');
    const repo = inject<Ref<Repo>>('repo');
    const apiClient = useApiClient();

    const loadedProcSlug = ref<string>();
    const procSlug = computed(() => `${repo?.value.owner} - ${repo?.value.name} - ${build.value.id} - ${procId.value}`);
    const proc = computed(() => build.value && findProc(build.value.procs || [], procId.value));
    const stream = ref<EventSource>();
    const log = ref<LogLine[]>();
    const consoleElement = ref<Element>();

    const loadedLogs = computed(() => !!log.value);
    const autoScroll = ref(true); // TODO: allow enable / disable
    const showActions = ref(false);
    const downloadInProgress = ref(false);
    const ansiUp = ref(new AnsiUp());
    ansiUp.value.use_classes = true;
    const logBuffer = ref<LogLine[]>([]);
    const flushTimer = ref<number>();

    const maxLineCount = 500; // TODO: think about way to support lazy-loading more than last 300 logs (#776)

    function formatTime(time?: number): string {
      return time === undefined ? '' : `${time}s`;
    }

    function writeLog(line: LogLine) {
      logBuffer.value.push({
        index: line.index ?? 0,
        text: ansiUp.value.ansi_to_html(line.text),
        time: line.time ?? 0,
      });
    }

    function scrollDown() {
      nextTick(() => {
        if (!consoleElement.value) {
          return;
        }
        consoleElement.value.scrollTop = consoleElement.value.scrollHeight;
      });
    }

    const flushLogs = debounce(() => {
      let buffer = logBuffer.value.slice(-maxLineCount);
      logBuffer.value = [];

      if (buffer.length === 0) {
        return;
      }

      // append old logs lines
      if (buffer.length < maxLineCount && log.value) {
        buffer = [...log.value.slice(-(maxLineCount - buffer.length)), ...buffer];
      }

      // deduplicate repeating times
      buffer = buffer.reduce(
        (acc, line) => ({
          lastTime: line.time ?? 0,
          lines: [
            ...acc.lines,
            {
              ...line,
              time: acc.lastTime === line.time ? undefined : line.time,
            },
          ],
        }),
        { lastTime: -1, lines: [] as LogLine[] },
      ).lines;

      log.value = buffer;

      if (autoScroll.value) {
        scrollDown();
      }
    }, 100);

    async function download() {
      if (!repo?.value || !build.value || !proc.value) {
        throw new Error('The repository, build or proc was undefined');
      }
      let logs;
      try {
        downloadInProgress.value = true;
        logs = await apiClient.getLogs(repo.value.owner, repo.value.name, build.value.number, proc.value.pid);
      } catch (e) {
        notifications.notifyError(e, i18n.t('repo.build.log_download_error'));
        return;
      } finally {
        downloadInProgress.value = false;
      }
      const fileURL = window.URL.createObjectURL(
        new Blob([logs.map((line) => line.out).join('')], {
          type: 'text/plain',
        }),
      );
      const fileLink = document.createElement('a');

      fileLink.href = fileURL;
      fileLink.setAttribute(
        'download',
        `${repo.value.owner}-${repo.value.name}-${build.value.number}-${proc.value.name}.log`,
      );
      document.body.appendChild(fileLink);

      fileLink.click();
      document.body.removeChild(fileLink);
      window.URL.revokeObjectURL(fileURL);
    }

    async function loadLogs() {
      if (loadedProcSlug.value === procSlug.value) {
        return;
      }
      loadedProcSlug.value = procSlug.value;
      log.value = [];
      logBuffer.value = [];
      ansiUp.value = new AnsiUp();
      ansiUp.value.use_classes = true;
      if (flushTimer.value) {
        window.clearInterval(flushTimer.value);
        flushTimer.value = undefined;
      }

      if (!repo) {
        throw new Error('Unexpected: "repo" should be provided at this place');
      }

      if (stream.value) {
        stream.value.close();
      }

      // we do not have logs for skipped jobs
      if (
        !repo.value ||
        !build.value ||
        !proc.value ||
        proc.value.state === 'skipped' ||
        proc.value.state === 'killed'
      ) {
        return;
      }

      if (isProcFinished(proc.value)) {
        const logs = await apiClient.getLogs(repo.value.owner, repo.value.name, build.value.number, proc.value.pid);
        logs.forEach((line) => writeLog({ index: line.pos, text: line.out, time: line.time }));
        flushLogs();
      }

      if (isProcRunning(proc.value)) {
        // load stream of parent process (which receives all child processes logs)
        // TODO: change stream to only send data of single child process
        stream.value = apiClient.streamLogs(
          repo.value.owner,
          repo.value.name,
          build.value.number,
          proc.value.ppid,
          (line) => {
            if (line?.proc !== proc.value?.name) {
              return;
            }
            writeLog({ index: line.pos, text: line.out, time: line.time });
            flushLogs();
          },
        );
      }
    }

    onMounted(async () => {
      loadLogs();
    });

    watch(procSlug, () => {
      loadLogs();
    });

    watch(proc, (oldProc, newProc) => {
      if (oldProc && oldProc.name === newProc?.name && oldProc?.end_time !== newProc?.end_time) {
        if (autoScroll.value) {
          scrollDown();
        }
      }
    });

    return { consoleElement, proc, log, loadedLogs, formatTime, showActions, download, downloadInProgress };
  },
});
</script>
```

**Comment by lafriks** [comment]
@anbraten done with minor change to not scroll log to bottom if showing finished job log

File: web/src/components/repo/build/BuildLog.vue [hunk 3]
```diff
@@ -163,9 +227,9 @@ export default defineComponent({
         return;
       }
       loadedProcSlug.value = procSlug.value;
-      loadedLogs.value = false;
-      term.value.reset();
-      term.value.write('\x1b[?25l');
+      log.value = [];
+      logBuffer.value = [];
+      ansiUp.value = new AnsiUp();
```
Comment (anbraten) [inline web/src/components/repo/build/BuildLog.vue:232]:
```suggestion
      ansiUp.value = new AnsiUp();
      ansiUp.value.use_classes = true;
```

File: web/src/components/repo/build/BuildLog.vue [hunk 4]
```diff
@@ -205,87 +264,34 @@ export default defineComponent({
...
-              if (autoScroll.value) {
-                term.value.scrollToBottom();
-              }
-            });
+          (line) => {
+            if (line?.proc !== proc.value?.name) {
+              return;
+            }
+            writeLog({ index: line.pos, text: line.out, time: line.time });
+            flushLogs(true);
```
Comment (anbraten) [inline web/src/components/repo/build/BuildLog.vue:272]: Instead of passing a `scroll` argument to `flushLogs` we could directly add the scroll call here and remove it from `flushLogs`.

```suggestion
            flushLogs();
            if (autoScroll.value) {
              scrollDown();
            }
```

Comment (lafriks) [reply web/src/components/repo/build/BuildLog.vue:272]: not really, as `flushLog` will be debounced to my understanding it could be called after specified interval only, so scrolling can't really be moved out otherwise it could be that lines will be added for display only after scroll has already been adjusted.

Comment (anbraten) [reply web/src/components/repo/build/BuildLog.vue:273]: Good point, missed that.

**Review by anbraten — APPROVED** [review]

File: web/src/components/repo/build/BuildLog.vue [hunk 5]
```diff
@@ -116,80 +120,29 @@ export default defineComponent({
...
     const proc = computed(() => build.value && findProc(build.value.procs || [], procId.value));
     const stream = ref<EventSource>();
-    const log = ref<LogLine[]>([]);
+    const log = ref<LogLine[]>();
     const consoleElement = ref<Element>();
 
-    const loadedLogs = ref(true);
-    const autoScroll = ref(true); // TODO
+    const loadedLogs = computed(() => !!log.value);
+    const autoScroll = ref(true); // TODO: allow enable / disable
```
Comment (6543) [inline web/src/components/repo/build/BuildLog.vue:127]: oh nice :+1:

**Review by 6543 — APPROVED** [review]
