### PR TITLE
Show oauth host and favicon on login

### LINKED ISSUE #5240: Login button displays `--forge-url` instead of `--forge-oauth-host`
### Component

web-ui

### Describe the bug

Image

Login works as expected, only the button text can confuse users.

### Steps to reproduce

Flags:
  - --server-host=https://ci.example.org
  - --server-webhook-host=http://woodpecker.testing.svc.cluster.local
  - --forgejo
  - --forge-url=http://forgejo.testing.svc.cluster.local
  - --forge-oauth-host=https://git.example.org
  - --forge-oauth-client=...

### Expected behavior

Button displays value of flag `--forge-oauth-host` if present.

### System Info

```shell
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"3.6.0"}
```

### Additional context

_No response_

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]

### PR DESCRIPTION
**Pull request by anbraten**
closes #5240

image

### CODE REVIEW

File: web/src/views/Login.vue [hunk 1]
```diff
@@ -100,4 +102,19 @@ onMounted(async () => {
 });
 
 useWPTitle(computed(() => [i18n.t('login')]));
+
+function getHostFromUrl(forge: Forge) {
+  if (!forge.url && !forge.oauth_host) {
+    return forge.type.charAt(0).toUpperCase() + forge.type.slice(1);
```
Comment (qwerty287) [inline web/src/views/Login.vue:108]: How should that happen?

Comment (anbraten) [reply web/src/views/Login.vue:108]: Addon forges would have an empty url

File: web/src/assets/locales/en.json [hunk 2]
```diff
@@ -1,8 +1,7 @@
 {
   "cancel": "Cancel",
-  "login_with": "Login with {forge}",
+  "login_to_woodpecker_with": "Login to Woodpecker with",
```
Comment (lafriks) [inline web/src/assets/locales/en.json:3]: "Login with X" imho is better
