### PR TITLE
fix(agent): workflow runner use shutdown context

### LINKED ISSUE #5925: Cancelling a workflow/run does not stop execution on runners (machines keep running)
### Component

server

### Describe the bug

When I cancel a workflow/run from the UI, the run is marked Canceled, but the underlying runner machines continue executing the job steps (tests keep running) and keep consuming runner capacity.

This creates wasted compute + blocks other jobs even though the UI shows the run is canceled.

Repo / Workflow
	•	Repo: provusinc/quoting
	•	Run/Pipeline: #133264 (“Nightly test flake”)
	•	Jobs observed still running after cancel:
	•	nightly-ui-regression-test on machine-5
	•	nightly-ui-regression-test on machine-6
	•	nightly-ui-regression-test on machine-7

Impact
	•	Wasted compute time
	•	Runner capacity stays blocked even though the run is canceled
	•	Confusing UX (UI says canceled but machines keep running)

### Steps to reproduce

1.	Trigger the workflow (ex: nightly-ui-regression-test).
2.	Wait until runners start executing (ex: after clone / restore-cache, during test).
3.	Click Cancel on the run/workflow.
4.	Observe the UI shows the step/run as canceled.

### Expected behavior

	Cancelling the run should:
    	•	send a cancel/terminate signal to all in-progress jobs on runners
    	•	stop current steps (or at minimum terminate the running process)
    	•	free runner capacity quickly

### System Info

```shell
Woodpecker 3.11.0
```

### Additional context

Image

### Validations

- [x] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [x] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [x] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/versions]

### PR DESCRIPTION
**Pull request by Pnkcaht**
## What was happening

When a workflow/run was canceled from the UI or API, the server correctly marked the run as Canceled, but the runner machines continued executing job steps.

Specifically:

- The cancel signal was received by the runner
- The workflow state was updated on the server
- Pipeline execution on the runner was not interrupted
- Tests and other long-running steps kept running and consuming runner capacity

This resulted in:

- Wasted compute time
- Runner capacity remaining blocked
- Confusing UX (UI shows Canceled, but jobs keep running)

## Related issue

Closes #5925

## Related PRs

This change complements previous cancellation-related fixes:

- #6018 — fixes container cleanup on step cancellation  
- #6020 — ensures DestroyStep runs on pipeline cancellation

While those PRs focus on step and backend cleanup, this PR ensures that workflow cancellation is properly propagated to the runner execution context.

## What this PR changes

This PR ensures that canceling a workflow immediately stops execution on the runner.

- Propagates server-side cancel events to the runner workflow context
- Cancels the workflow execution context as soon as a cancel signal is received
- Ensures pipeline execution and backend steps are interrupted
- Normalizes cancellation handling so the workflow consistently ends as Canceled

## Why this approach

In Woodpecker, the workflow context is the single source of truth for execution lifecycle.

Previously, receiving a cancel event did not reliably cancel the workflow execution context, allowing pipeline steps to continue running.
By explicitly canceling the workflow context when a cancel signal is received:

- The pipeline runtime receives context.Done()
- Backend implementations (Docker, Kubernetes, etc.) can terminate running steps
- Runner capacity is freed promptly

This aligns runner behavior with what the UI reports and avoids wasted resources.

## Implementation overview

```mermaid
sequenceDiagram
    participant UI as Web UI / API
    participant Server as Woodpecker Server
    participant Runner as Agent Runner
    participant Pipeline as Pipeline Runtime
    participant Backend as Backend Engine

    UI->>Server: Cancel workflow
    Server->>Runner: Cancel signal (Wait)
    Runner->>Runner: cancel workflow context
    Runner->>Pipeline: ctx.Done()
    Pipeline->>Backend: stop execution
    Backend-->>Pipeline: terminate running steps
    Pipeline-->>Runner: execution aborted
    Runner->>Server: report canceled state
```

### CODE REVIEW

File: agent/runner.go [hunk 1]
```diff
@@ -89,57 +88,74 @@ func (r *Runner) Run(runnerCtx, shutdownCtx context.Context) error { //nolint:co
...
 	workflowCtx = utils.WithContextSigtermCallback(workflowCtx, func() {
-		logger.Error().Msg("Received sigterm termination signal")
+		logger.Error().Msg("received sigterm termination signal")
+		cancel()
 	})
 
-	canceled := false
+	// canceled indicates whether the workflow was canceled remotely (UI/API).
+	// Must be atomic because it is written from a goroutine and read later.
+	var canceled atomic.Bool
```
Comment (6543) [inline agent/runner.go:104]: well I'm working on that right now too ...  #6011

-> lets see that to merge in first and how ...

**Comment by 6543** [comment]
@Pnkcaht for you as you are new to the project i just documented a bunch of dev stuff:

https://github.com/woodpecker-ci/woodpecker/pull/6012
https://github.com/woodpecker-ci/woodpecker/pull/6019

-> https://woodpecker-ci-woodpecker-pr-6019.surge.sh/docs/next/development/architecture

File: agent/runner.go (hunk 1 above)
Comment (ghost) [reply agent/runner.go:104]: okok :)

File: agent/runner.go [hunk 2]
```diff
@@ -53,10 +54,11 @@ func NewRunner(workEngine rpc.Peer, f rpc.Filter, h string, state *State, backen
 func (r *Runner) Run(runnerCtx, shutdownCtx context.Context) error { //nolint:contextcheck
```
Comment (6543) [inline agent/runner.go]:
```suggestion
func (r *Runner) Run(runnerCtx, shutdownCtx context.Context) error {
```

**Comment by 6543** [comment]
before the patch:

if you cancle the agent while running a workflow the steps and workflow is marked as failed

now:

workfow is correctly stated as failed but the step is marked as success

**Comment by ghost** [comment]
@6543 What do you think?   :)

image

**Comment by 6543** [comment]
sorry wont do ... the steps are marked as succes the state of the whole workflow is not the problem

File: agent/runner.go [hunk 3]
```diff
@@ -50,13 +51,14 @@ func NewRunner(workEngine rpc.Peer, f rpc.Filter, h string, state *State, backen
...
 }
 
-func (r *Runner) Run(runnerCtx, shutdownCtx context.Context) error { //nolint:contextcheck
+func (r *Runner) Run(runnerCtx, shutdownCtx context.Context) error {
 	log.Debug().Msg("request next execution")
 
+	// Preserve metadata AND cancellation from runnerCtx.
 	meta, _ := metadata.FromOutgoingContext(runnerCtx)
-	ctxMeta := metadata.NewOutgoingContext(context.Background(), meta)
+	ctxMeta := metadata.NewOutgoingContext(runnerCtx, meta)
```
Comment (6543) [inline agent/runner.go]: this context is used to report back things ... and if a workfow is cancled this should still work

Comment (6543) [reply agent/runner.go]: that might be the issue here...!

we most propably should have an shutdown context for the agent that shuld be passed into here

Comment (ghost) [reply agent/runner.go]: I understand, I agree, is there anything that can be done?

Comment (6543) [inline agent/runner.go]:
```suggestion
	ctxMeta := metadata.NewOutgoingContext(shutdownCtx, meta)
```

Comment (6543) [reply agent/runner.go]: that works - tested ...through at local backend i had some glitches that needs to be locked ito where the step status was first failed and after a second was updated to success ... but that should be another related but other issue.

**Comment by ghost** [comment]
Can you explain the mistakes you made? I can fix them.

File: agent/runner.go [hunk 4]
```diff
@@ -89,57 +88,74 @@ func (r *Runner) Run(runnerCtx, shutdownCtx context.Context) error { //nolint:co
...
+		Started: time.Now().Unix(),
+	}
 
-	err = r.client.Init(runnerCtx, workflow.ID, state)
-	if err != nil {
+	// Initialize workflow on the server
+	if err := r.client.Init(runnerCtx, workflow.ID, state); err != nil {
 		logger.Error().Err(err).Msg("workflow initialization failed")
-		// TODO: should we return here?
+		// Do not return here: even if init fails, we still need to run the pipeline
```
Comment (6543) [inline agent/runner.go]: https://github.com/woodpecker-ci/woodpecker/pull/6011/changes#diff-6d787b427ac08cd61669af7e34ff0b747c4264d20b31b21b681a2ec2c826d9f0R152-R156

i would say make this line untouche i handle it in the other pull

Comment (ghost) [reply agent/runner.go]: Gotcha, I changed the comment and left it there. If you need anything else in the pull request you're working on, just tag me

File: agent/runner.go [hunk 5]
```diff
@@ -151,40 +164,42 @@ func (r *Runner) Run(runnerCtx, shutdownCtx context.Context) error { //nolint:co
 			"pipeline_number": pipelineNumber,
 		}),
 	).Run(runnerCtx)
+	// If the workflow context was canceled but the pipeline returned no error,
+	// force a cancellation error so running steps are not reported as success.
+	if err == nil && workflowCtx.Err() != nil {
+		err = pipeline.ErrCancel
+	}
```
Comment (6543) [inline agent/runner.go]:
```suggestion
```

Comment (ghost) [reply agent/runner.go]: okok

File: agent/runner.go [hunk 6]
```diff
@@ -154,37 +167,34 @@ func (r *Runner) Run(runnerCtx, shutdownCtx context.Context) error { //nolint:co
...
+		err = pipeline.ErrCancel
 	}
 
 	if err != nil {
 		state.Error = err.Error()
 	}
 
 	logger.Debug().
+		Bool("canceled", canceled.Load()).
 		Str("error", state.Error).
```
Comment (6543) [inline agent/runner.go]:
```suggestion
		Str("error", state.Error).
		Bool("canceled", canceled.Load()).
```

**Comment by 6543** [comment]
this intorduced an regression, proper fix is https://github.com/woodpecker-ci/woodpecker/pull/6361
