### PR TITLE
Use global branch filter only on events containing branch info

### LINKED ISSUE #581: Gitea tag event: Step does not start
### Component

server

### Describe the bug

I tried to get my first steps with woodpeckerci, pipelines on a git-`push` work fine, but when I create a new tag woodpecker shows:
* Endless spinning wheel (circular progress)
* `This step has been canceled.` in the build view (`.../build/1/4`)
* `Not yet started` on the right menu

Trying to click on `cancel` even does not work (error: `An unknown error occured`).

I used a slightly modified docker-compose from the docs, and also tried the 0.14.3 release (docker image), but that version did not start at all (see last log).

### System Info

`/version`:
```json
{"source":"https://github.com/woodpecker-ci/woodpecker","version":"next-"}
```

docker-compose.yml:
```yaml
version: '3'

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    restart: always
    ports:
      - 8000:8000
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_ORGS=Xxx
      - WOODPECKER_ADMIN=xxx,yyy
      - WOODPECKER_REPO_OWNERS=Xxxx
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=${WOODPECKER_GITEA_URL}
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_MAX_PROCS=2
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}

volumes:
  woodpecker-server-data:
```

Docker version `20.10.9-ce, build 79ea9d308018`
docker-compose version `1.25.1, build a82fef0`

### Additional context

latest docker log (before trying to cancel):
```
woodpecker-server_1  | {"level":"warn","error":"sql: no rows in result set","time":"2021-12-08T17:20:04Z"}
woodpecker-agent_1   | {"level":"error","error":"rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: \"too_many_pings\"","time":"2021-12-08T17:20:12Z","message":"grpc error: done(): code: Unavailable: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: \"too_many_pings\""}
woodpecker-agent_1   | {"level":"error","error":"rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: \"too_many_pings\"","time":"2021-12-08T17:20:12Z","message":"grpc error: done(): code: Unavailable: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: \"too_many_pings\""}
woodpecker-server_1  | {"level":"error","time":"2021-12-08T17:21:00Z","message":"failure to parse token from hook for XXX/xxx-yyy. signature is invalid"}
woodpecker-server_1  | {"level":"error","error":"Error #01: signature is invalid\n","ip":"172.22.0.1","latency":0.803823,"method":"POST","path":"/hook","status":400,"time":"2021-12-08T17:21:00Z","user-agent":"Go-http-client/1.1","time":"2021-12-08T17:21:00Z"}
```

Additional when clicking on cancel:
```
woodpecker-server_1  | {"level":"error","error":"Error #01: queue: task not found\n","ip":"172.22.0.1","latency":1.759874,"method":"DELETE","path":"/api/repos/XXX/xxx-yyy/builds/1/1","status":500,"time":"2021-12-08T17:30:08Z","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0","time":"2021-12-08T17:30:08Z"}
```

Log for 0.14.3 release with docker (UI never starts)
```
woodpecker-server_1  | time="2021-12-08T17:18:15Z" level=error msg="unable to open database file: no such file or directory"
woodpecker-server_1  | time="2021-12-08T17:18:15Z" level=fatal msg="database ping attempts failed"
woodpecker-agent_1   | 2021/12/08 17:18:15 grpc error: done(): code: Unavailable: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.22.0.3:9000: connect: connection refused"
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy).

### PR DESCRIPTION
**Pull request by 6543**
- close #581
- delete unused code
- simplify code

bug was introduce at eed92421c940dc18508338fc1858ab5370bea51f (regression of #32)

### CODE REVIEW

File: server/shared/procBuilder.go [hunk 1]
```diff
@@ -138,9 +137,24 @@ func (b *ProcBuilder) Build() ([]*BuildItem, error) {
 
 	items = filterItemsWithMissingDependencies(items)
 
+	// check if at least one proc can start
```
Comment (6543) [inline server/shared/procBuilder.go:140]:
```suggestion
	// check if at least one proc can start, if list is not empty
```

**Review by jolheiser — APPROVED** [review]
