### PR TITLE
Report status for detached steps and services

### LINKED ISSUE #2831: Service step doesn't change its status
### Component

web-ui

### Describe the bug

Running pipeline with a service, it doesn't change its status and logs are empty unless page are reloaded.

Pipeline:
```yaml
services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306
steps:
  get-version:
    image: ubuntu
    commands:
      - ( apt update && apt dist-upgrade -y && apt install -y mysql-client 2>&1 )> /dev/null
      - sleep 60s # need to wait for mysql-server init
      - echo 'SHOW VARIABLES LIKE "version"' | mysql -uroot -hdatabase test -pexample
```

Start pipeline and click on the service step - logs exist:
Screenshot 2023-11-16 152141

Then switch to the general step and wait to complete - there are logs, status changes to completed, execution timer stops:
Screenshot 2023-11-16 152553

Switch back to the service - now there are no logs, step is executing forever:
Screenshot 2023-11-16 152702

After page reloading, all displays as expected - logs, status and execution timer:
Screenshot 2023-11-16 152756

The later should be without refreshing page.

### System Info

```shell
2.0.0-rc.0, Kubernetes
```

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Checked that the bug isn't fixed in the `next` version already [https://woodpecker-ci.org/faq#which-version-of-woodpecker-should-i-use]
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### LINKED ISSUE #6033: services / detached steps dont report backe if they end early
## TODOs:

services dont report back when they are finished:
image

similar issue for detached steps:
image

because both are just droped into the background:
https://github.com/woodpecker-ci/woodpecker/blob/8b6c814666244d2bc0619aa4c636803b08631db8/pipeline/pipeline.go#L276-L279

_Originally posted by @6543 in https://github.com/woodpecker-ci/woodpecker/issues/6011#issuecomment-3809192468_

### PR DESCRIPTION
**Pull request by 6543**
image
image
image

 ---
close #6033
resolve #2831

### CODE REVIEW

**Comment by 6543** [comment]
TODO: restructure pipeline/*.go to use submodules



- pipeline/error.go -> pipeline/errors/...
- pipeline/pipeline.go#Runtime -> pipeline/runtime/runtime.go
- pipeline/pipeline.go#execAll -> pipeline/runtime/executor.go
- pipeline/shutdown.go -> pipeline/runtime/shutdown.go
- pipeline/logger.go ->pipeline/logging
- pipeline/tracer.go -> pipeline/tracing
- X -> state/state.go?
- ...

**Comment by anbraten** [comment]
I would argue detached steps and services should let a pipeline fail. For example if you are testing a database / woodpecker server in some kind of integration test if they crash or fail the pipeline should be marked as failed as well. Users could still use "/bin/mytool || exit 0" if there service is likely to fail and should be ignored

**Comment by 6543** [comment]
in this regards there is also the option to ignore errors...

**Comment by 6543** [comment]
I'll test to see what a common case will do right now (mariadb & postgress as db)

**Comment by 6543** [comment]
image
well needs more work on that front ...

**Comment by 6543** [comment]
# Now
## expl. failing services and detached
image
## normal have them succeed
image

**Comment by 6543** [comment]
```
5:42PM ERR agent/rpc/client_grpc.go:181 > grpc error: wait(): code: Unknown error="rpc error: code = Unknown desc = workflow finished with error "                                                 
5:42PM ERR agent/runner.go:112 > server returned unexpected err while waiting for workflow to finish run error="rpc error: code = Unknown desc = workflow finished with error " pipeline=129 repo=test/test-bash-ci workflow_id=129  
```

fixed by https://github.com/woodpecker-ci/woodpecker/pull/6039/commits/4e5d5db30b90268e51c8b4860d33918130077d49

**Comment by 6543** [comment]
the approach how it's done is not the simplest code ... but I would like to move refactoring that stuff in a new pull after https://github.com/woodpecker-ci/woodpecker/pull/6073 got merged witch is based on this pull :)

File: pipeline/backend/docker/docker.go [hunk 1]
```diff
@@ -304,13 +309,24 @@ func (e *docker) DestroyStep(ctx context.Context, step *backend.Step, taskUUID s
 	log.Trace().Str("taskUUID", taskUUID).Msgf("stop step %s", step.Name)
 
 	containerName := toContainerName(step)
+	var stopErr error
+
+	// we first signal to the container to stop ...
+	if err := e.client.ContainerStop(ctx, containerName, container.StopOptions{
+		Timeout: &containerKillTimeout,
+	}); err != nil && !isErrContainerNotFoundOrNotRunning(err) {
+		// we do not return error jet as we try to kill it first
```
Comment (qwerty287) [inline pipeline/backend/docker/docker.go]: A "jet" is a plane…

```suggestion
		// we do not return error yet as we try to kill it first
```

Comment (6543) [reply pipeline/backend/docker/docker.go]: aaaa  well human written comment ... i try to get that common mispell out of my head.

thanks

**Review by qwerty287 — APPROVED** [review]
Seems fine as well, but also untested.

File: pipeline/pipeline.go [hunk 2]
```diff
@@ -233,23 +233,43 @@ func (r *Runtime) execAll(runnerCtx context.Context, steps []*backend.Step) <-ch
...
+				}
+				return err
 			}
 
-			// Return the error after tracing it.
-			err = r.traceStep(processState, err, step)
-			if err != nil && step.Failure == metadata.FailureIgnore {
-				return nil
+			// we report all errors till setup happened
+			// afterwards they just ged dropped
```
Comment (anbraten) [inline pipeline/pipeline.go:259]: Please check for typos and gramma! Tools like cspell, deepl or AI (there are also offline solutions) can really help!

```suggestion
			// Report all errors until the setup happened.
			// Afterwards errors will be dropped.
```

Comment (qwerty287) [reply pipeline/pipeline.go:259]: sorry, I missed that as well

Comment (6543) [reply pipeline/pipeline.go:259]: -> https://github.com/woodpecker-ci/woodpecker/pull/6095

PS I do use tools, but most of them miss gramma. as for AI i do use it but it's not integrated into my IDE so i have to explizite give it code snippets or text to check for gramma ... I try to do it more
