### PR TITLE
Refresh token when running cron

### LINKED ISSUE #1431: The users token is not refreshed when running cron jobs -> cron jobs stop working
### Component

server

### Describe the bug

When executiing cron jobs woodpecker uses the oauth token of the user who created the cron job to authenticate against the forge. Once this token is expired woodpecker can no longer authenticate and execution of the cron jobs fails.

To fix this, woodpecker has to refresh the token using the refresh token stored in the database.

### System Info

```shell
latest next version run from docker
```

### Additional context

Will submit a PR soon.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/woodpecker-ci/woodpecker/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://woodpecker-ci.org/docs/intro).
- [X] Check that there isn't [already an issue](https://github.com/woodpecker-ci/woodpecker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/fcMQqSMXJy) or the [Matrix room](https://matrix.to/#/#woodpecker:matrix.org).

### PR DESCRIPTION
**Pull request by smainz**
Before accessing a repo during a cron job the users token is refreshed like it is done for e.g. create pipeline. User in this context means the creator of the cron job.

fixes #1431

If the scheduled delay between two executions of a cron job is larger than the exiration time of the oauth2 refresh token (provided by the forge) this will fail and the cron job will not be run. But this is the best one can do.

### CODE REVIEW

File: server/cron/cron.go [hunk 1]
```diff
@@ -121,7 +122,23 @@ func CreatePipeline(ctx context.Context, store store.Store, forge forge.Forge, c
 		return nil, nil, err
 	}
 
-	commit, err := forge.BranchHead(ctx, creator, repo, cron.Branch)
+	// if the forge has a refresh token, the current access token
+	// may be stale. Therefore, we should refresh prior to dispatching
+	// the pipeline.
+	if refresher, ok := server.Config.Services.Forge.(forge.Refresher); ok {
```
Comment (6543) [inline server/cron/cron.go:128]:
```suggestion
	if refresher, ok := f.(forge.Refresher); ok {
```
shouldnt this also work?

Comment (smainz) [reply server/cron/cron.go]: It does :-)

Updated

**Comment by smainz** [comment]
Why doesn't the local 'make lint' find what is found in the CI server?

Code_RQTtytNddt

**Review by lafriks — APPROVED** [review]
