### PR TITLE
Fix: Agent now gracefully handles running containers when killed

### LINKED ISSUE #6016: Agent does not shutdown docker backend propperly
```
12:41PM DBG agent/tracer.go:62 > update step status complete exit_code=0 exited=false image=bash pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM DBG pipeline/pipeline.go:228 > executing pipeline_number=24 repo=test/test-bash-ci step="sleep 30s" workflow_id=24
12:41PM DBG agent/logger.go:44 > log stream opened image=bash pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM DBG agent/rpc/client_grpc.go:413 > log drain: sending queued logs bytes=128 entries=3
^C12:41PM ERR agent/runner.go:101 > Received sigterm termination signal pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM INF cmd/agent/main.go:38 > termination signal is received, shutting down agent
12:41PM DBG agent/logger.go:51 > log stream copied, close ... image=bash pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM DBG pipeline/pipeline.go:234 > complete pipeline_number=24 repo=test/test-bash-ci step="sleep 30s" workflow_id=24
12:41PM DBG agent/tracer.go:54 > update step status error="error during connect: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.51/containers/wp_01KFX1PYGQY8BNAAFTMKNNPA46/json\": received signal: 0xc000226a80" exit_code=126 exited=true image=bash pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM DBG cmd/agent/core/agent.go:232 > unregister agent from server ...
12:41PM DBG cmd/agent/core/agent.go:281 > terminating health reporting
12:41PM DBG agent/runner.go:128 > pipeline done pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM DBG agent/rpc/client_grpc.go:167 > grpc error: wait(): context canceled error="rpc error: code = Canceled desc = context canceled"
12:41PM INF cmd/agent/core/agent.go:102 > shutdown healthcheck server ...
12:41PM ERR pipeline/backend/docker/docker.go:326 > could not kill container 'sleep 30s' error="error during connect: Post \"http://%2Fvar%2Frun%2Fdocker.sock/v1.51/containers/wp_01KFX1PYGQY8BNAAFTMKNNPA46/kill?signal=9\": received signal: 0xc000116000"
12:41PM INF cmd/agent/core/agent.go:106 > healthcheck server stopped
12:41PM DBG agent/runner.go:120 > done listening for cancel signal pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM ERR pipeline/backend/docker/docker.go:329 > could not remove container 'sleep 30s' error="error during connect: Delete \"http://%2Fvar%2Frun%2Fdocker.sock/v1.51/containers/wp_01KFX1PYGQY8BNAAFTMKNNPA46?v=1\": received signal: 0xc000116000"
12:41PM INF cmd/agent/core/agent.go:238 > agent unregistered from server
12:41PM ERR pipeline/backend/docker/docker.go:334 > could not remove volume 'wp_01kfx1pygqy8bnaaftmjg5k71s_0_default' error="error during connect: Delete \"http://%2Fvar%2Frun%2Fdocker.sock/v1.51/volumes/wp_01kfx1pygqy8bnaaftmjg5k71s_0_default?force=1\": received signal: 0xc000116000"
12:41PM ERR pipeline/backend/docker/docker.go:337 > could not remove network 'wp_01kfx1pygqy8bnaaftmjg5k71s_0_default' error="error during connect: Delete \"http://%2Fvar%2Frun%2Fdocker.sock/v1.51/networks/wp_01kfx1pygqy8bnaaftmjg5k71s_0_default\": received signal: 0xc000116000"
12:41PM DBG agent/runner.go:179 > workflow finished error=Canceled canceled=true pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM DBG agent/runner.go:181 > uploading logs and traces / states ... pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM DBG agent/tracer.go:62 > update step status complete error="error during connect: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.51/containers/wp_01KFX1PYGQY8BNAAFTMKNNPA46/json\": received signal: 0xc000226a80" exit_code=126 exited=true image=bash pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM DBG agent/runner.go:183 > uploaded logs and traces / states pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM DBG agent/runner.go:187 > updating workflow status error=Canceled pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM DBG agent/runner.go:196 > updating workflow status complete pipeline=24 repo=test/test-bash-ci workflow_id=24
12:41PM INF cmd/agent/core/agent.go:76 > shutdown of whole agent
```

### PR DESCRIPTION
**Pull request by Pnkcaht**
### What was happening
When a pipeline step was canceled (e.g. manual cancel or agent shutdown), the Docker backend would stop waiting for the container but **would not actively terminate it**.  
This caused containers running long-lived commands (like `sleep`, `tail -f`, servers, etc.) to continue running in the background.

## Related Issue
Closes #6016 

### What this PR changes
This PR ensures that **when the step context is canceled**, the running Docker container is **immediately killed**.

- Listens to `ctx.Done()` in `WaitStep`
- Sends a `ContainerKill` using a non-cancelable context
- Preserves existing behavior for normal container exit
- Prevents orphaned containers after pipeline cancellation

### Why this approach
Docker containers do not automatically stop when the caller context is canceled.  
Explicitly killing the container on `ctx.Done()` guarantees correct cleanup and matches expected CI behavior.

### Implementation overview
```mermaid
sequenceDiagram
    participant Engine as Pipeline Engine
    participant Docker as Docker Backend
    participant Ctx as Step Context
    participant C as Container

    Engine->>Docker: StartStep
    Docker->>C: docker run
    Docker->>Docker: WaitStep (ContainerWait)

    alt Pipeline canceled
        Ctx-->>Docker: ctx.Done()
        Docker->>C: ContainerKill (SIGKILL)
        Docker->>Docker: ContainerWait returns
    else Step finishes normally
        C-->>Docker: container exits
    end

    Docker-->>Engine: Step state (exit code)
```

## How it was tested

- Manually reproduced the issue with long-running containers
- Verified that containers remain running without this fix
- Verified that containers are killed immediately after cancellation with this fix
- Ran go test ./pipeline/backend/docker

### Test pipeline configuration

To reproduce the issue and validate the fix, a minimal Woodpecker pipeline was used with `skip_clone: true` and a long-running step.

```yaml
skip_clone: true

steps:
  sleep_30s:
    image: bash
    commands:
      - echo wait 30s
      - sleep 30s
      - echo wait done
```

## Terminal Output 

The behavior was validated using a long-running Docker container to simulate a pipeline step that does not exit on its own.

**Before the fix**
- Canceling the step would stop waiting, but the container kept running.

**After the fix**
- Canceling the step immediately terminates the running container.

Example manual verification:

image

### CODE REVIEW

File: pipeline/backend/docker/docker.go [hunk 1]
```diff
@@ -264,6 +282,9 @@ func (e *docker) WaitStep(ctx context.Context, step *backend.Step, taskUUID stri
 		log.Trace().Msgf("ContainerWait returned with err: %v", err)
```
Comment (6543) [inline pipeline/backend/docker/docker.go:282]: can we not achive the same if we just add a new case here that does `		case <-ctx.Done():` ?

Comment (ghost) [reply pipeline/backend/docker/docker.go:282]: Good question :)

Simply adding a `case <-ctx.Done()` to the existing select is not enough, because when the context is canceled, **all Docker API calls using that context are also canceled**.

In this case, `ContainerWait` returns, but we lose the ability to reliably call `ContainerKill`, since the same canceled context would be used.

That’s why the fix explicitly:
- listens for `ctx.Done()`
- uses a **non-cancelable context** to call `ContainerKill`
- guarantees the container is actually terminated, not just “detached” from

Otherwise, the behavior remains the same: the step stops waiting, but the container may keep running.

Comment (6543) [reply pipeline/backend/docker/docker.go:282]: right ... just one nit :)

File: pipeline/backend/docker/docker.go [hunk 2]
```diff
@@ -250,11 +250,29 @@ func (e *docker) StartStep(ctx context.Context, step *backend.Step, taskUUID str
...
 	log.Trace().Msgf("wait for step %s", step.Name)
 
 	containerName := toContainerName(step)
+	done := make(chan struct{})
+
+	// Ensure container is killed if context is canceled (SIGTERM / pipeline cancel)
+	go func() {
+		select {
+		case <-ctx.Done():
+			_ = e.client.ContainerKill(context.Background(), containerName, "9")
```
Comment (6543) [inline pipeline/backend/docker/docker.go]: I just wonder why DestroyStep is not exec it should do that in any case whether wait errors or not

sure this is good enouth for a hotfix and we can merge it for now... but there is an underlaying issue upwards the call stack (i asum)

File: pipeline/backend/docker/docker.go (hunk 1 above)
Comment (ghost) [reply pipeline/backend/docker/docker.go:282]: > right ... just one nit :)

Thank you and I agree, any detail, even the smallest, is appreciated; I want the code to be perfect :)

File: pipeline/backend/docker/docker.go (hunk 2 above)
Comment (ghost) [reply pipeline/backend/docker/docker.go]: Agreed. DestroyStep should ideally handle this.
This fix addresses the current gap where DestroyStep is not called on cancellation, preventing orphaned containers.
A broader fix higher in the call stack would be needed to fully address this, and I’m happy to follow up with a separate PR to tackle that if it makes sense.

Comment (6543) [inline pipeline/backend/docker/docker.go]:
```suggestion
			_ = e.client.ContainerKill(context.Background(), containerName, "9") //nolint:contextcheck
```

**Comment by 6543** [comment]
**hotfix** removed in  #6011 as solved propperly

(as per https://github.com/woodpecker-ci/woodpecker/pull/6018#discussion_r2728558699)
